import SwiftUI

enum RelayLanguage: String, CaseIterable, Identifiable {
    case chinese = "zh-Hans"
    case japanese = "ja"
    case english = "en"

    static let defaultsKey = "interfaceLanguage"

    var id: String { rawValue }

    var nativeName: String {
        switch self {
        case .chinese: "简体中文"
        case .japanese: "日本語"
        case .english: "English"
        }
    }

    static func load(from defaults: UserDefaults = .standard) -> RelayLanguage {
        guard let rawValue = defaults.string(forKey: defaultsKey),
              let language = RelayLanguage(rawValue: rawValue) else {
            return .chinese
        }
        return language
    }

    func save(to defaults: UserDefaults = .standard) {
        defaults.set(rawValue, forKey: Self.defaultsKey)
    }
}

struct RelayCopy {
    let language: RelayLanguage

    /// Keys are the English source copy, so English is the identity table.
    func text(_ key: String) -> String {
        switch language {
        case .chinese: Self.chinese[key] ?? key
        case .japanese: Self.japanese[key] ?? key
        case .english: key
        }
    }

    func taskStatus(_ status: RelayTaskStatus) -> String {
        switch (language, status) {
        case (.chinese, .queued): "排队中"
        case (.chinese, .starting): "启动中"
        case (.chinese, .running): "运行中"
        case (.chinese, .waitingForApproval): "等待审批"
        case (.chinese, .waitingForInput): "等待输入"
        case (.chinese, .completed): "已完成"
        case (.chinese, .failed): "失败"
        case (.chinese, .canceled): "已取消"
        case (.japanese, .queued): "待機中"
        case (.japanese, .starting): "起動中"
        case (.japanese, .running): "実行中"
        case (.japanese, .waitingForApproval): "承認待ち"
        case (.japanese, .waitingForInput): "入力待ち"
        case (.japanese, .completed): "完了"
        case (.japanese, .failed): "失敗"
        case (.japanese, .canceled): "キャンセル済み"
        case (.english, .queued): "Queued"
        case (.english, .starting): "Starting"
        case (.english, .running): "Running"
        case (.english, .waitingForApproval): "Awaiting approval"
        case (.english, .waitingForInput): "Awaiting input"
        case (.english, .completed): "Completed"
        case (.english, .failed): "Failed"
        case (.english, .canceled): "Canceled"
        }
    }

    func daemonState(_ state: DaemonState) -> String {
        switch (language, state) {
        case (.chinese, .connecting): "连接中"
        case (.chinese, .online): "在线"
        case (.chinese, .offline): "离线"
        case (.japanese, .connecting): "接続中"
        case (.japanese, .online): "オンライン"
        case (.japanese, .offline): "オフライン"
        case (.english, .connecting): "CONNECTING"
        case (.english, .online): "ONLINE"
        case (.english, .offline): "OFFLINE"
        }
    }

    func agentHealth(_ health: RelayAgentHealth) -> String {
        switch (language, health) {
        case (.chinese, .checking): "检查中"
        case (.chinese, .ready): "可用"
        case (.chinese, .missing): "未找到"
        case (.chinese, .invalid): "无效"
        case (.japanese, .checking): "確認中"
        case (.japanese, .ready): "使用可能"
        case (.japanese, .missing): "未検出"
        case (.japanese, .invalid): "無効"
        case (.english, .checking): "CHECKING"
        case (.english, .ready): "READY"
        case (.english, .missing): "MISSING"
        case (.english, .invalid): "INVALID"
        }
    }

    func threadFilter(_ filter: RelayThreadFilter) -> String {
        switch (language, filter) {
        case (.chinese, .all): "全部"
        case (.chinese, .active): "进行中"
        case (.chinese, .waiting): "等待中"
        case (.chinese, .failed): "失败"
        case (.chinese, .done): "已结束"
        case (.japanese, .all): "すべて"
        case (.japanese, .active): "実行中"
        case (.japanese, .waiting): "待機中"
        case (.japanese, .failed): "失敗"
        case (.japanese, .done): "終了"
        case (.english, .all): "All"
        case (.english, .active): "Active"
        case (.english, .waiting): "Waiting"
        case (.english, .failed): "Failed"
        case (.english, .done): "Done"
        }
    }

    func outputKind(_ kind: RelayOutputKind) -> String {
        switch (language, kind) {
        case (.chinese, .user): "你"
        case (.chinese, .assistant): "智能体"
        case (.chinese, .tool): "工具"
        case (.chinese, .system): "系统"
        case (.chinese, .error): "错误"
        case (.japanese, .user): "あなた"
        case (.japanese, .assistant): "エージェント"
        case (.japanese, .tool): "ツール"
        case (.japanese, .system): "システム"
        case (.japanese, .error): "エラー"
        case (.english, .user): "You"
        case (.english, .assistant): "Agent"
        case (.english, .tool): "Tool"
        case (.english, .system): "System"
        case (.english, .error): "Error"
        }
    }

    func codexMode(_ mode: RelayCodexMode) -> String {
        switch (language, mode) {
        case (.chinese, .defaultMode): "默认"
        case (.chinese, .plan): "计划"
        case (.japanese, .defaultMode): "デフォルト"
        case (.japanese, .plan): "計画"
        case (.english, .defaultMode): "Default"
        case (.english, .plan): "Plan"
        }
    }

    func chainPlaceholder(count: Int) -> String {
        guard count >= 2 else {
            return text("Click at least two agents to build a chain…")
        }
        switch language {
        case .chinese: return "发送给 \(count) 个接力步骤的任务…"
        case .japanese: return "\(count) ステップのチェーンに送るタスク…"
        case .english: return "Task to send through \(count) relay steps…"
        }
    }

    func comparePlaceholder(count: Int) -> String {
        guard count >= 2 else {
            return text("Check at least two agents to compare…")
        }
        switch language {
        case .chinese: return "并行发送给 \(count) 个智能体的任务…"
        case .japanese: return "\(count) 個のエージェントへ並列送信するタスク…"
        case .english: return "Task to send to \(count) agents in parallel…"
        }
    }

    func taskPlaceholder(agentName: String) -> String {
        switch language {
        case .chinese: "描述一个交给 \(agentName) 的任务…"
        case .japanese: "\(agentName) に依頼するタスクを入力…"
        case .english: "Describe a task for \(agentName)…"
        }
    }

    private static let chinese: [String: String] = [
        "Settings": "设置",
        "General": "通用",
        "Agents": "智能体",
        "Interface language": "界面语言",
        "Changes the language used by Relay. CLI output and agent replies stay unchanged.": "切换 Relay 自身界面的语言。CLI 输出和智能体回答保持原文。",
        "Default working directory": "默认工作目录",
        "Used when creating a new thread. Existing threads keep their own working directory.": "创建新线程时使用。已有线程保留各自的工作目录。",
        "Choose…": "选择…",
        "RECENT PROJECTS": "最近项目",
        "Choose project folder…": "选择项目文件夹…",
        "Switch project": "切换项目",
        "New windows use this project": "新窗口使用此项目",
        "PAIR": "双开",
        "Open Claude and Codex for this project": "为当前项目同时打开 Claude 与 Codex",
        "Claude and Codex must both be available.": "Claude 与 Codex 必须都可用",
        "Not enough terminal slots for this project pair.": "终端空位不足，无法双开当前项目",
        "OUTPUT": "输出",
        "REVIEW": "待看",
        "NEXT": "下一项",
        "BACK": "返回",
        "CONTEXT RELAY": "上下文接力",
        "CONTEXT FORK": "上下文分叉",
        "Carry this screen into one native CLI": "把当前画面交给另一个原生 CLI",
        "Carry this screen into one or more native CLIs": "把当前画面分叉给一个或多个原生 CLI",
        "LOCAL MEMORY · 48 KB MAX": "仅内存 · 最多 48 KB",
        "FROM": "来源",
        "TO": "目标",
        "Relay current terminal screen to another CLI": "把当前终端画面接力给另一个 CLI",
        "Fork current terminal screen into one or more CLIs": "把当前终端画面分叉给一个或多个 CLI",
        "Open another terminal to receive this context.": "请先打开另一个终端接收此上下文",
        "Finish the current prompt flow before relaying context.": "请先完成当前提示词流程，再接力上下文",
        "No terminal text to relay.": "当前终端没有可接力的文字",
        "Close and clear captured context": "关闭并清除已截取的上下文",
        "Confirm this target is at an input prompt, then select it": "确认目标 CLI 已停在输入框后再选择",
        "What should the next CLI do with this context?": "希望下一个 CLI 如何处理这段上下文？",
        "CURRENT SCREEN SNAPSHOT · EDIT BEFORE FILLING": "当前画面快照 · 填入前可编辑",
        "Captured only when you opened this panel · no clipboard or disk": "仅在打开面板时截取 · 不进剪贴板、不写磁盘",
        "FILL TARGET · DOES NOT RUN": "填入目标 · 不执行",
        "FILL ⟨N⟩ TARGETS · DOES NOT RUN": "填入 ⟨N⟩ 个目标 · 不执行",
        "Close context relay before opening prompt stage": "请先关闭上下文接力，再打开提示词暂存台",
        "Close context fork before opening prompt stage": "请先关闭上下文分叉，再打开提示词暂存台",
        "Close result confluence before opening prompt stage": "请先关闭结果汇流，再打开提示词暂存台",
        "Receiving terminal output": "终端正在输出",
        "Terminal output needs review": "此终端有待查看输出",
        "Receiving terminal output, output needs review": "终端正在输出，且有待查看输出",
        "Focus latest terminal output": "跳到最近输出的终端",
        "Review next terminal output": "查看下一个有待查看输出的终端",
        "Next action: review a staged prompt · ⟨N⟩ pending · ⌥⌘J": "下一步：核对暂存提示词 · 共 ⟨N⟩ 项待处理 · ⌥⌘J",
        "Next action: review unseen output · ⟨N⟩ pending · ⌥⌘J": "下一步：查看未读输出 · 共 ⟨N⟩ 项待处理 · ⌥⌘J",
        "Focus latest terminal output · ⌥⌘J": "跳到最近输出的终端 · ⌥⌘J",
        "Return to ⟨CLI⟩ · ⌥⌘K": "返回 ⟨CLI⟩ · ⌥⌘K",
        "PROMPT STAGE": "提示词暂存台",
        "Prepare once, fill several native CLIs": "写一次，填入多个原生 CLI",
        "FILL ONLY · DOES NOT RUN": "仅填入 · 不执行",
        "Close prompt stage": "关闭提示词暂存台",
        "Fill this terminal without running": "填入此终端但不执行",
        "This CLI has not enabled safe paste yet": "此 CLI 尚未启用安全粘贴",
        "READY TO FILL": "可填入",
        "NOT READY": "未就绪",
        "Write once, then fill every selected CLI…": "写一次，再填入所有选中的 CLI…",
        "Only CLIs with safe paste enabled can be selected.": "只能选择已启用安全粘贴的 CLI。",
        "Confirm each CLI is at an input prompt before selecting it.": "请先确认每个 CLI 已停在输入框，再手动选择。",
        "Confirm this CLI is at an input prompt, then select it": "确认此 CLI 已停在输入框后再选择",
        "SELECTED": "已选择",
        "CONFIRM PROMPT": "请确认输入框",
        "SAFE PASTE UNAVAILABLE": "安全粘贴不可用",
        "FILL": "填入",
        "Filled into ⟨N⟩ terminals · Return was not pressed": "已填入 ⟨N⟩ 个终端 · 没有按下回车",
        "REVIEW TERMINALS": "查看终端",
        "Fill one prompt into several terminals without running it": "将同一提示词填入多个终端但不执行",
        "Hide prompt review; progress is kept": "收起提示词核对；进度会保留",
        "Open completed prompt review": "打开已完成的提示词核对",
        "Resume prompt review · ⟨N⟩ left": "继续提示词核对 · 还剩 ⟨N⟩ 个",
        "PROMPT REVIEW": "提示词核对",
        "DECISION BRIEF REVIEW": "决策简报核对",
        "Check the filled CLI before you run it": "执行前核对已填入的 CLI",
        "DECISION BRIEF · ⟨BYTES⟩ UTF-8 B · ⟨RESULT⟩": "决策简报 · ⟨BYTES⟩ UTF-8 字节 · ⟨RESULT⟩",
        "FULL RESULT": "完整结果",
        "BACK TO DECISION": "返回决策",
        "BACK TO CLI REVIEW": "返回 CLI 核对",
        "CAPTURE ACTION RECEIPT": "冻结行动回执",
        "VIEW ACTION RECEIPT": "查看行动回执",
        "Open the unsaved in-memory action receipt": "打开尚未保存的内存行动回执",
        "Freeze the exact filled brief and current visible screen; this does not claim success": "冻结准确的已填简报与当前可见画面；这不代表执行成功",
        "Return to the checkpoint; filled text stays in the CLI": "返回检查点；已填文字仍保留在 CLI 中",
        "Check each native CLI in order": "按顺序核对每个原生 CLI",
        "RETURN NOT SENT": "未发送回车",
        "RETURN NOT DETECTED": "未检测到回车",
        "RETURN ⏎ ⟨COUNT⟩ / ⟨TOTAL⟩": "检测到回车 ⏎ ⟨COUNT⟩ / ⟨TOTAL⟩",
        "Close review; filled text stays in the terminals": "关闭核对；已填内容仍保留在终端",
        "Hide review; progress and filled text stay in place": "收起核对；进度与终端内已填内容都会保留",
        "This terminal closed before review": "此终端在核对前已关闭",
        "Reviewed; select to revisit this terminal": "已核对；点击可重新查看",
        "Currently reviewing this terminal": "正在核对此终端",
        "Select this terminal to review it": "点击核对此终端",
        "CLOSED": "已关闭",
        "CHECKED": "已检查",
        "CURRENT": "当前核对",
        "PENDING": "待核对",
        "ALL TARGETS CHECKED": "全部目标已核对",
        "REVIEW ENDED": "核对已结束",
        "Return was never sent. Run each CLI when you decide.": "始终没有发送回车。请在决定后自行运行各 CLI。",
        "Closed targets were not counted as checked. Return was never sent.": "已关闭的目标不计为已核对。始终没有发送回车。",
        "REVIEWING ⟨CURRENT⟩ OF ⟨TOTAL⟩": "正在核对 ⟨CURRENT⟩ / ⟨TOTAL⟩",
        "Prompt cleared from Relay. Check the terminal input line.": "提示词已从 Relay 清除。请检查终端输入行。",
        "⟨CHECKED⟩ checked · ⟨CLOSED⟩ closed · Return not sent": "已核对 ⟨CHECKED⟩ · 已关闭 ⟨CLOSED⟩ · 未发送回车",
        "NEW PROMPT": "新提示词",
        "END REVIEW": "结束核对",
        "End review; filled text stays in the terminals": "结束并清除核对进度；已填内容仍保留在终端",
        "Prompt text cleared · Return remains yours": "正文已清除 · 回车仍由你决定",
        "RESULT CONFLUENCE": "结果汇流",
        "⟨N⟩ CLI screens frozen at one explicit moment": "一次明确截取 · 冻结 ⟨N⟩ 个 CLI 画面",
        "LOCAL MEMORY · EXPLICIT SNAPSHOT": "仅内存 · 显式截取",
        "Close and clear collected screens": "关闭并清除已汇流画面",
        "LIVE CLI": "实时 CLI",
        "CLI CLOSED": "CLI 已关闭",
        "Focus live CLI": "查看实时 CLI",
        "Captured together only when you clicked · no clipboard or disk": "仅在点击时同步截取 · 不进剪贴板、不写磁盘",
        "RECAPTURE": "重新截取",
        "BACK TO REVIEW": "返回核对",
        "CAPTURE CURRENT SCREENS": "汇流当前画面",
        "Freeze reviewed CLI screens together for local comparison": "将已核对 CLI 的当前画面冻结在一起，本地对照",
        "Finish checking every target before collecting screens.": "请先核对全部目标，再汇流画面。",
        "Keep at least two reviewed terminals open to collect screens.": "请至少保留两个已核对终端，以便汇流画面。",
        "Keep every collected terminal open to recapture screens.": "重新截取前，请保持所有已汇流终端处于打开状态。",
        "RESULT ARBITRATION": "结果裁决",
        "ARBITRATE RESULTS": "裁决这些结果",
        "Give one CLI every frozen screen": "把全部冻结画面交给一个 CLI",
        "FROZEN RESULTS · FILL ONLY": "冻结结果 · 仅填入",
        "What should the deciding CLI do with these results?": "希望裁决 CLI 如何处理这些结果？",
        "ARBITER": "裁决目标",
        "⟨N⟩ frozen sources · 64 KB max": "⟨N⟩ 个冻结来源 · 最多 64 KB",
        "PAYLOAD PREFLIGHT": "载荷预检",
        "FULL": "完整",
        "TAIL KEPT": "已截尾",
        "UTF-8 BYTES · NO TOKEN GUESS": "UTF-8 字节 · 不猜 token",
        "Enter an instruction to preview exact local bytes": "输入裁决指令后预检准确的本地字节数",
        "ARBITRATION SOURCES": "裁决来源",
        "⟨N⟩ frozen screens behind this arbitration": "本次裁决背后的 ⟨N⟩ 个冻结画面",
        "LOCAL MEMORY · READ ONLY": "仅限内存 · 只读",
        "BACK TO ARBITER REVIEW": "返回裁决核对",
        "VIEW ⟨N⟩ FROZEN SOURCES · ⟨BYTES⟩ B": "查看 ⟨N⟩ 个冻结来源 · ⟨BYTES⟩ B",
        "View the exact frozen screens staged for this arbitration": "查看本次裁决实际填入的冻结画面",
        "⟨N⟩ SOURCES · ⟨BYTES⟩ B STAGED": "已填入 ⟨N⟩ 个来源 · ⟨BYTES⟩ B",
        "CHECK LIVE DRIFT": "检查实时变化",
        "UNCHANGED": "未变化",
        "CHANGED": "已变化",
        "Compare each frozen source with its live visible screen once": "将每个冻结来源与当前可见画面比较一次",
        "DECISION SEAL": "决策封存",
        "Frozen sources → exact payload → arbiter result": "冻结来源 → 精确载荷 → 裁决结果",
        "EXPLICIT · LOCAL MEMORY · READ ONLY": "显式操作 · 仅限内存 · 只读",
        "FROZEN SOURCES": "冻结来源",
        "EXACT PAYLOAD": "精确载荷",
        "UTF-8 BYTES": "UTF-8 字节",
        "⟨N⟩ frozen sources": "⟨N⟩ 个冻结来源",
        "ARBITER RESULT": "裁决结果",
        "SEALED": "已封存",
        "Sealed only when you clicked · no clipboard or disk": "仅在点击时封存 · 不进剪贴板、不写磁盘",
        "SEAL RESULT": "封存结果",
        "VIEW SEALED RESULT": "查看封存结果",
        "DECISIONS": "决策",
        "DECISION LIBRARY": "决策库",
        "PRIVATE LOCAL FILES": "私有本地文件",
        "Close decision library": "关闭决策库",
        "SEARCH DECISIONS": "搜索决策",
        "Search agent, project, evidence, result or ID": "搜索智能体、项目、证据、结果或 ID",
        "Search title, tag, agent, project, evidence, result or ID": "搜索标题、标签、智能体、项目、证据、结果或 ID",
        "Clear decision search": "清除决策搜索",
        "No matching decisions": "没有匹配的决策",
        "PIN DECISION": "置顶决策",
        "UNPIN DECISION": "取消置顶",
        "EDIT LABEL": "编辑标签",
        "CLOSE LABEL": "关闭标签",
        "PRIVATE DECISION LABEL": "私有决策标签",
        "ACTION RECEIPTS · ⟨N⟩": "行动回执 · ⟨N⟩",
        "CURRENT SCREENS · NOT SUCCESS PROOF": "当前画面 · 不代表执行成功",
        "Open this private action receipt": "打开这份私有行动回执",
        "DECISION ACTION RECEIPT": "决策行动回执",
        "SAVED PRIVATE · 0600": "已私有保存 · 0600",
        "UNSAVED · LOCAL MEMORY": "未保存 · 仅本地内存",
        "DISCARD UNSAVED RECEIPT": "丢弃未保存回执",
        "DISCARD TO DECISION": "丢弃并返回决策",
        "The unsaved in-memory receipt will be discarded.": "尚未保存的内存回执将被丢弃。",
        "SEALED DECISION": "已封存决策",
        "USER RETURN DETECTED": "已检测到用户回车",
        "RELAY DID NOT SEND IT": "不是由 Relay 发送",
        "CURRENT SCREEN": "当前画面",
        "EXACT FILLED DECISION BRIEF": "准确的已填决策简报",
        "TAIL KEPT · ⟨KEPT⟩ / ⟨TOTAL⟩ B": "保留尾部 · ⟨KEPT⟩ / ⟨TOTAL⟩ 字节",
        "FULL SEALED RESULT": "完整封存结果",
        "CAPTURED CURRENT SCREEN": "已冻结的当前画面",
        "VISIBLE AT CAPTURE TIME · NOT A SUCCESS CLAIM": "截取时可见 · 不代表执行成功",
        "This receipt proves the captured chain only; it does not prove task completion or success.": "此回执只证明被冻结的因果链；不证明任务已完成或执行成功。",
        "SAVE PRIVATE RECEIPT": "保存私有回执",
        "RECOVER IN LIVE CLI": "在实时 CLI 中恢复",
        "RECEIPT → LIVE CLI RECOVERY": "回执 → 实时 CLI 恢复",
        "FROZEN EVIDENCE · FILL ONLY": "冻结证据 · 仅填入",
        "FROZEN SCREEN": "冻结画面",
        "Optional next instruction for the recovered CLI…": "给恢复目标 CLI 的可选后续指令…",
        "Relay carries the exact receipt into one prompt-ready CLI and leaves Return to you.": "Relay 会把准确回执填入一个已就绪 CLI；回车仍由你决定。",
        "⟨KEPT⟩ / ⟨TOTAL⟩ B SCREEN": "画面保留 ⟨KEPT⟩ / ⟨TOTAL⟩ 字节",
        "Frozen receipt stays unchanged · no clipboard or disk": "冻结回执保持不变 · 不进剪贴板、不写磁盘",
        "ACTION RECOVERY REVIEW": "行动恢复核对",
        "Check the recovered CLI before you run it": "执行前核对恢复到 CLI 的内容",
        "ACTION RECOVERY · ⟨BYTES⟩ UTF-8 B · ⟨SCREEN⟩": "行动恢复 · ⟨BYTES⟩ UTF-8 字节 · ⟨SCREEN⟩",
        "BACK TO ACTION RECEIPT": "返回行动回执",
        "Return to the frozen receipt; filled text stays in the CLI": "返回冻结回执；已填文字仍保留在 CLI 中",
        "RECOVERY CHANGES · ⟨N⟩": "恢复变化 · ⟨N⟩",
        "VISIBLE SCREEN EVIDENCE · NOT SUCCESS PROOF": "可见画面证据 · 不代表执行成功",
        "Open this private recovery change": "打开这份私有恢复变化",
        "RECOVERY CHANGE RECEIPT": "恢复变化回执",
        "DISCARD UNSAVED RECOVERY CHANGE": "丢弃未保存的恢复变化",
        "DISCARD TO ACTION RECEIPT": "丢弃并返回行动回执",
        "The unsaved recovery screen will be discarded.": "尚未保存的恢复画面将被丢弃。",
        "BACK TO RECOVERY REVIEW": "返回恢复核对",
        "FROZEN RECEIPT SCREEN": "冻结回执画面",
        "RECOVERY SCREEN": "恢复后画面",
        "VISIBLE SCREEN CHANGE": "可见画面变化",
        "SCREEN EVIDENCE · NOT SUCCESS PROOF": "画面证据 · 不代表执行成功",
        "This receipt records a visible change only; it does not prove completion or success.": "此回执只记录可见画面的变化；不证明任务完成或执行成功。",
        "SAVE PRIVATE RECOVERY CHANGE": "保存私有恢复变化",
        "VIEW RECOVERY CHANGE": "查看恢复变化",
        "Open the unsaved in-memory recovery screen comparison": "打开尚未保存的内存恢复画面对比",
        "CAPTURE RECOVERY CHANGE": "截取恢复变化",
        "Compare the current visible screen with the frozen receipt; this does not claim success": "将当前可见画面与冻结回执对比；不代表执行成功",
        "CONTINUE CHANGE IN LIVE CLI": "把变化接力到实时 CLI",
        "RECOVERY CHANGE → LIVE CLI": "恢复变化 → 实时 CLI",
        "PRIVATE LINEAGE · FILL ONLY": "私有血缘 · 仅填入",
        "Optional instruction for the next CLI…": "给下一 CLI 的可选指令…",
        "Relay carries both recorded screens into one prompt-ready CLI and leaves Return to you.": "Relay 会把两份已记录画面填入一个已就绪 CLI；回车仍由你决定。",
        "⟨FROZEN⟩ / ⟨FROZEN_TOTAL⟩ B FROZEN · ⟨RECOVERY⟩ / ⟨RECOVERY_TOTAL⟩ B RECOVERY": "冻结画面保留 ⟨FROZEN⟩ / ⟨FROZEN_TOTAL⟩ B · 恢复画面保留 ⟨RECOVERY⟩ / ⟨RECOVERY_TOTAL⟩ B",
        "Saved change stays unchanged · no clipboard or disk": "已保存变化保持不变 · 不进剪贴板、不写磁盘",
        "RECOVERY CHANGE HANDOFF REVIEW": "恢复变化接力核对",
        "Check the relayed recovery change before you run it": "执行前核对接力到 CLI 的恢复变化",
        "RECOVERY HANDOFF · ⟨BYTES⟩ UTF-8 B · ⟨SCREENS⟩": "恢复接力 · ⟨BYTES⟩ UTF-8 B · ⟨SCREENS⟩",
        "BOTH SCREENS FULL": "两份画面完整",
        "SCREEN TAIL KEPT": "画面已截尾",
        "BACK TO RECOVERY CHANGE": "返回恢复变化",
        "Return to the saved recovery change; filled text stays in the CLI": "返回已保存的恢复变化；已填文字仍保留在 CLI 中",
        "Finish the current prompt flow before relaying a recovery change.": "请先完成当前提示词流程，再接力恢复变化。",
        "The recovery change handoff does not fit the local prompt limit.": "恢复变化接力超过本地提示词上限。",
        "Confirm one live target is at an input prompt before relaying the change.": "接力变化前，请确认一个实时目标停在输入框。",
        "RECOVERY CHANGE WITNESS": "恢复变化见证",
        "DISCARD UNSAVED RECOVERY WITNESS": "丢弃未保存的恢复变化见证",
        "DISCARD TO RECOVERY CHANGE": "丢弃并返回恢复变化",
        "The unsaved witness screen and assessment will be discarded.": "尚未保存的见证画面与判断将被丢弃。",
        "BACK TO WITNESS REVIEW": "返回见证核对",
        "RECOVERY CHANGE": "恢复变化",
        "EXACT HANDOFF": "准确接力载荷",
        "WITNESS SCREEN": "见证画面",
        "EXACT HANDOFF PAYLOAD": "准确接力载荷",
        "WITNESS VISIBLE SCREEN": "见证时可见画面",
        "VIEW WITNESS SCREEN": "查看见证画面",
        "VIEW EXACT HANDOFF": "查看准确接力载荷",
        "YOUR WITNESS ASSESSMENT": "你的见证判断",
        "SUPPORTS CHANGE": "支持变化",
        "RAISES CONCERN": "发现问题",
        "INCONCLUSIVE": "无法判断",
        "USER-LABELED · RELAY DOES NOT JUDGE": "由用户标记 · Relay 不自动判断",
        "This witness records the exact handoff and visible review; it does not prove completion or correctness.": "此见证记录准确接力载荷与可见核对结果；不证明任务完成或结果正确。",
        "SAVE PRIVATE WITNESS": "保存私有见证",
        "RECOVERY WITNESSES · ⟨N⟩": "恢复见证 · ⟨N⟩",
        "Open this private recovery witness": "打开这份私有恢复见证",
        "VIEW RECOVERY WITNESS": "查看恢复见证",
        "Open the unsaved in-memory recovery witness": "打开尚未保存的内存恢复见证",
        "CAPTURE RECOVERY WITNESS": "截取恢复见证",
        "Freeze the exact handoff and current witness screen; Relay does not judge it": "冻结准确接力载荷与当前见证画面；Relay 不自动判断",
        "Return must be detected before capturing a recovery witness.": "检测到用户亲自回车后才能截取恢复见证。",
        "Keep the witness CLI open with a visible screen before capturing.": "截取前请保持见证 CLI 打开且画面可见。",
        "Recovery witness saved locally.": "恢复见证已保存在本机。",
        "Could not save the recovery witness.": "无法保存恢复见证。",
        "COMPARE WITNESSES": "对照见证",
        "Compare two saved recovery witnesses without judging them": "对照两份已保存恢复见证，但不代替判断",
        "WITNESS COMPARISON": "见证对照",
        "LEFT WITNESS": "左侧见证",
        "RIGHT WITNESS": "右侧见证",
        "SELECT TWO WITNESSES": "选择两份见证",
        "Choose one saved witness for each side; the same record cannot occupy both sides.": "左右各选一份已保存见证；同一记录不能同时占据两侧。",
        "SAME EXACT HANDOFF": "准确接力相同",
        "DIFFERENT EXACT HANDOFF": "准确接力不同",
        "USER LABELS MATCH": "人工标注相同",
        "USER LABELS DIFFER": "人工标注分歧",
        "WITNESS SCREEN DIFFERENCE": "见证画面差异",
        "LEFT WITNESS SCREEN": "左侧见证画面",
        "RIGHT WITNESS SCREEN": "右侧见证画面",
        "⟨PAYLOAD⟩ B HANDOFF · ⟨SCREEN⟩ B SCREEN": "接力 ⟨PAYLOAD⟩ B · 画面 ⟨SCREEN⟩ B",
        "Both saved witnesses stay unchanged; Relay does not judge them.": "两份已保存见证均保持不变；Relay 不代替判断。",
        "4 FROZEN SOURCES · FILL ONLY": "4 份冻结来源 · 仅填入",
        "PROMPT-READY TARGET": "已就绪输入目标",
        "Optional instruction for the comparison reviewer…": "给对照审阅 CLI 的可选指令…",
        "Relay fills one comparison packet; it never runs the target or chooses a winner.": "Relay 只填入一份对照包；不会执行目标，也不会代替裁决。",
        "LEFT HANDOFF": "左侧接力",
        "LEFT SCREEN": "左侧画面",
        "RIGHT HANDOFF": "右侧接力",
        "RIGHT SCREEN": "右侧画面",
        "MERGE": "汇聚",
        "UTF-8 B COMPARISON PACKET": "UTF-8 B 对照包",
        "Confirm one live target is at an input prompt before relaying witnesses.": "接力见证前，请确认一个实时目标停在输入框。",
        "SELECT": "选择",
        "Decision title": "决策标题",
        "Tags separated by commas": "用逗号分隔标签",
        "SAVE LABEL": "保存标签",
        "Title and tags are stored separately; frozen evidence stays unchanged": "标题与标签独立保存；冻结证据保持不变",
        "8 TAGS MAX · 24 CHARACTERS EACH": "最多 8 个标签 · 每个 24 字",
        "EVIDENCE READ ONLY · PRIVATE 0600": "证据只读 · 私有文件 0600",
        "SAVE PRIVATE CHECKPOINT": "保存私有检查点",
        "Writes this frozen chain to Relay Application Support": "将这条冻结决策链写入 Relay 的 Application Support",
        "CHECKPOINT SAVED": "已保存",
        "OPEN DECISION LIBRARY": "打开决策库",
        "DECISION CHECKPOINT": "决策检查点",
        "PRIVATE LOCAL FILE · 0600 · READ ONLY": "私有本地文件 · 0600 · 只读",
        "CHECKPOINT REPLAY": "检查点重裁决",
        "Frozen evidence reopened · parent stays unchanged": "重新打开冻结证据 · 父检查点保持不变",
        "PARENT CHECKPOINT · READ ONLY": "父检查点 · 只读",
        "ARCHIVED SOURCE": "存档来源",
        "Parent checkpoint stays unchanged · no clipboard or disk": "父检查点保持不变 · 不进剪贴板、不写磁盘",
        "RE-ARBITRATE FROM CHECKPOINT": "从检查点重新裁决",
        "Re-evaluate this frozen evidence with any live CLI": "将这份冻结证据交给任一实时 CLI 重新评估",
        "CONTINUE FROM DECISION": "从此决策继续",
        "Carry this sealed result into one live CLI without running it": "将封存结果填入一个实时 CLI，但不执行",
        "DECISION → ACTION BRIDGE": "决策 → 行动桥",
        "LOCAL · FILL ONLY · DOES NOT RUN": "仅本地 · 只填入 · 不执行",
        "SEALED RESULT": "封存结果",
        "UTF-8 B": "UTF-8 字节",
        "Optional next instruction for the target CLI…": "给目标 CLI 的可选后续指令…",
        "Relay adds checkpoint provenance, fills one prompt-ready CLI, and leaves Return to you.": "Relay 会附上检查点来源并填入一个已就绪 CLI；回车仍由你决定。",
        "⟨KEPT⟩ / ⟨TOTAL⟩ B RESULT": "结果保留 ⟨KEPT⟩ / ⟨TOTAL⟩ 字节",
        "Select this prompt-ready CLI": "选择这个已停在输入框的 CLI",
        "OPEN A TERMINAL TO CHOOSE A TARGET": "请先打开终端以选择目标",
        "REOPEN ARBITRATION": "重新打开裁决",
        "BACK TO CHECKPOINT": "返回检查点",
        "REPLAY DECISION": "重裁决结果",
        "DERIVED CHECKPOINT · 0600": "派生检查点 · 0600",
        "VIEW PARENT": "查看父检查点",
        "REPLAY": "重裁决",
        "DECISION DELTA": "决策差异",
        "COMPARE RESULTS": "对比结果",
        "Parent result ↔ derived result": "父结果 ↔ 派生结果",
        "Reference result ↔ current result": "参考结果 ↔ 当前结果",
        "PARENT RESULT": "父结果",
        "DERIVED RESULT": "派生结果",
        "REFERENCE RESULT": "参考结果",
        "CURRENT RESULT": "当前结果",
        "READ-ONLY FILES · LOCAL DIFF": "只读文件 · 本地差异",
        "+⟨ADDED⟩ added · −⟨REMOVED⟩ removed · =⟨UNCHANGED⟩ unchanged": "+⟨ADDED⟩ 新增 · −⟨REMOVED⟩ 删除 · =⟨UNCHANGED⟩ 未变",
        "EARLIER LINES OMITTED": "已省略更早行",
        "LAST 64 KB · 300 LINES MAX": "末尾 64 KB · 最多 300 行",
        "BACK TO DERIVED": "返回派生检查点",
        "Parent and derived checkpoints stay unchanged": "父检查点与派生检查点均保持不变",
        "Compared checkpoints stay unchanged": "参与比较的检查点均保持不变",
        "LINEAGE": "决策血缘",
        "ROOT": "根节点",
        "CURRENT NODE": "当前节点",
        "CHILD": "派生",
        "PARENT MISSING": "父记录缺失",
        "CYCLE BLOCKED": "已阻断循环",
        "DEPTH LIMIT": "已达深度上限",
        "FAMILY LIMIT": "已达家族上限",
        "COMPARE LINEAGE": "比较血缘节点",
        "Compare any connected checkpoint": "比较同一血缘中的任意检查点",
        "Open checkpoint in lineage": "打开血缘中的检查点",
        "Finish the current prompt flow before replaying a checkpoint.": "请先完成当前提示词流程，再重裁决检查点。",
        "Finish the current prompt flow before continuing from a decision.": "请先完成当前提示词流程，再从决策继续。",
        "The decision brief does not fit the local prompt limit.": "决策简报超出本地提示词上限。",
        "Confirm one live target is at an input prompt before continuing.": "请确认一个实时目标 CLI 已停在输入框，再继续。",
        "Saved checkpoint sources cannot be recaptured.": "已保存检查点的来源不能重新截取。",
        "MOVE TO TRASH": "移入废纸篓",
        "The checkpoint file can be recovered from Trash.": "检查点文件可从废纸篓恢复。",
        "BACK TO LIBRARY": "返回决策库",
        "Explicit saves only · private files 0600 · deletion moves to Trash": "仅显式保存 · 私有文件 0600 · 删除会移入废纸篓",
        "No saved decisions": "尚无已保存决策",
        "OPEN": "打开",
        "saved decision checkpoints were ignored": "个已保存决策检查点已忽略",
        "private decision files were ignored": "个私有决策文件已忽略",
        "Decision checkpoint saved locally.": "决策检查点已保存到本地。",
        "Return must be detected before capturing an action receipt.": "检测到用户回车后才能冻结行动回执。",
        "Keep the target open with a visible screen before capturing a receipt.": "请保持目标 CLI 打开并显示可见画面，再冻结回执。",
        "Action receipt saved locally.": "行动回执已保存到本地。",
        "Could not save the action receipt.": "无法保存行动回执。",
        "Finish the current prompt flow before recovering from a receipt.": "请先完成当前提示词流程，再从回执恢复。",
        "The action recovery brief does not fit the local prompt limit.": "行动恢复简报超出本地提示词上限。",
        "Confirm one live target is at an input prompt before recovering.": "恢复前，请确认一个实时目标 CLI 已停在输入框。",
        "Return must be detected before capturing a recovery change.": "检测到用户回车后才能截取恢复变化。",
        "Keep the recovery target open with a visible screen before capturing.": "请保持恢复目标 CLI 打开并显示可见画面，再截取变化。",
        "Recovery change saved locally.": "恢复变化已保存到本地。",
        "Could not save the recovery change.": "无法保存恢复变化。",
        "Decision label is too long.": "决策标题或标签超出上限。",
        "Decision label saved locally.": "决策标签已保存到本地。",
        "Could not save the decision label.": "无法保存决策标签。",
        "Could not save the decision checkpoint.": "无法保存决策检查点。",
        "Could not load saved decision checkpoints.": "无法载入已保存的决策检查点。",
        "Could not move the decision checkpoint to Trash.": "无法将决策检查点移入废纸篓。",
        "Open the frozen arbiter result": "查看已冻结的裁决结果",
        "Freeze the arbiter's current visible screen into this decision chain": "将裁决 CLI 的当前可见画面冻结到这条决策链",
        "Finish checking the arbiter before sealing its result.": "请先核对裁决目标，再封存结果。",
        "Keep the reviewed arbiter open to seal its result.": "请保持已核对的裁决目标处于打开状态，再封存结果。",
        "FILL ARBITER · DOES NOT RUN": "填入裁决目标 · 不执行",
        "Give frozen results to one CLI without running them": "把冻结结果填入一个 CLI 但不执行",
        "Write an arbitration instruction that fits the local prompt limit.": "请填写符合本地提示词上限的裁决指令。",
        "Confirm one live target is at an input prompt before relaying results.": "请确认一个实时目标 CLI 已停在输入框，再填入结果。",
        "⟨N⟩ left": "还剩 ⟨N⟩ 个",
        "CHECKED · NEXT": "已检查 · 下一窗",
        "No edit key or Return detected": "未检测到编辑输入或回车",
        "Edit input detected; Return not detected": "检测到编辑输入 · 未检测到回车",
        "Return detected; Relay did not send it": "检测到用户回车 · 不是 Relay 发送",
        "Terminal restarted after the prompt was filled": "终端在填入提示词后已重启",
        "Terminal closed after the prompt was filled": "终端在填入提示词后已关闭",
        "⟨COUNT⟩ targets closed or restarted after filling · ⏎ ⟨RETURN⟩": "填入后有 ⟨COUNT⟩ 个目标关闭或重启 · ⏎ ⟨RETURN⟩",
        "Return detected in ⟨COUNT⟩ of ⟨TOTAL⟩ terminals. Relay did not send it.": "⟨TOTAL⟩ 个终端中有 ⟨COUNT⟩ 个检测到用户回车；不是 Relay 发送。",
        "No Return detected. Run each CLI when you decide.": "未检测到回车。请在决定后自行运行各 CLI。",
        "⟨CHECKED⟩ checked · ⏎ ⟨RETURN⟩ · ⟨ISSUES⟩ interrupted": "已核对 ⟨CHECKED⟩ · ⏎ ⟨RETURN⟩ · 受影响 ⟨ISSUES⟩",
        "System notifications": "系统通知",
        "Quick input bar": "全局快速输入条",
        "Press Option-Space anywhere to send a task to the background daemon.":
            "在任意应用中按 ⌥空格 呼出悬浮输入条，把任务交给后台 daemon。",
        "Send a task without leaving your app…": "不离开当前应用，直接发一个任务…",
        "Runs in the background — you'll get a notification.": "后台运行 —— 完成后会收到通知。",
        "Switch agent (Tab)": "切换智能体（Tab）",
        "TEMPLATES": "模板",
        "SAVE AS TEMPLATE": "存为模板",
        "Delete template": "删除模板",
        "Save this route as a template": "把当前链路存为模板",
        "Template name": "模板名称",
        "Cancel": "取消",
        "Daemon log": "daemon 日志",
        "relayd writes diagnostics to a local log file inside Application Support.":
            "relayd 的诊断信息会写入 Application Support 内的本地日志文件。",
        "Open log": "打开日志",
        "Close (Esc)": "关闭（Esc）",
        "SPLIT": "分屏",
        "TERMINALS": "终端",
        "NO TERMINALS": "没有终端",
        "Click an agent on the left": "点击左侧智能体",
        "to open its real CLI here": "在这里打开它的原生 CLI",
        "Terminal limit reached (4)": "最多同时开 4 个终端",
        "Drag to move": "拖动标题栏移动窗口，双击最大化",
        "Toggle maximize": "最大化 / 还原",
        "Freeze these answers and pick one CLI to arbitrate them":
            "冻结这些结构化回答，进入汇流面板选一个 CLI 裁决并可封存入决策库",
        "Need at least two non-empty results to arbitrate.": "至少需要两个非空结果才能汇流裁决。",
        "Remount daemon compare/chain groups as windows": "把 daemon 里的对比/串联任务组重新挂载为窗口（关 GUI 后仍在推进的链也能找回）",
        "No arbiter yet — open an agent's CLI terminal from the left sidebar and let it reach its input prompt.": "还没有可用的裁判——先在左侧点一个智能体打开它的 CLI 终端，等它停在输入框",
        "Continue the relay with a new message…": "继续接力：输入新一轮指令，依次经过同一条链…",
        "SEND": "发送",
        "A step has no resumable session — follow-up rounds are unavailable.":
            "有步骤没有可续会话（如 Ollama），无法追加轮次。",
        "You are in a multi-round roundtable with other AI agents (⟨OTHERS⟩).":
            "你正在与另外几位 AI 智能体（⟨OTHERS⟩）进行多轮圆桌对话。",
        "Since your last turn, the others said:": "在你上一轮之后，其他参与者说：",
        "PARTICIPANT": "参与者",
        "Pick 2–4 agents and a topic": "选择 2–4 个智能体并输入主题",
        "Add 2–4 participants in speaking order": "按发言顺序添加 2–4 个参与者",
        "Everyone keeps their own session; turns go around the table.":
            "每位参与者保有自己的会话记忆，发言按座次轮转。",
        "FORK TO TERMINALS": "分叉给终端",
        "Fill these answers into live CLI terminals":
            "把这些干净回答一次性填入 1–3 个开着的 CLI 终端（只填入，不执行）",
        "Minimize to the dock": "最小化到底部停靠条",
        "Restore this window": "恢复这个窗口",
        "ONE-CLICK VERDICT": "一键裁决",
        "⟨NAME⟩ is arbitrating — structured verdict, no terminal needed…":
            "⟨NAME⟩ 裁决中——结构化结论，无需终端…",
        "Pick an agent to judge these results headlessly; the verdict comes back structured and sealable.":
            "选一个智能体在后台阅卷：结论结构化返回、可直接封存；不用开终端、不用按回车",
        "no terminal · no Return": "无需终端 · 无需回车",
        "Moderator": "主持人",
        "Speak as the moderator — starts one more round…":
            "以主持人身份发言：所有参与者都会看到，并开启新一轮…",
        "Roundtable minutes": "圆桌纪要",
        "Transcript": "转录",
        "Save the transcript as a Markdown file": "把整场转录导出为 Markdown 文件",
        "⟨N⟩ approvals waiting — click to respond": "⟨N⟩ 项审批等待处理——点击进入",
        "Collapse sidebar": "收起侧栏（⌘\\）",
        "Expand sidebar": "展开侧栏（⌘\\）",
        "Isolated worktrees (git)": "隔离工作区（git worktree）",
        "Each agent codes in its own copy of the repo; adopt the winning diff afterwards.":
            "每个智能体在仓库的独立分身里改代码、互不践踏；跑完可一键采纳优胜改动",
        "The current project is not a git repository — worktree isolation is unavailable.":
            "当前项目不是 git 仓库，无法隔离工作区",
        "Isolated worktree: ⟨PATH⟩": "隔离分身：⟨PATH⟩",
        "ADOPT THIS VERSION": "采纳此版",
        "Apply this worktree's diff onto the project": "把这个分身的全部改动并入主项目",
        "Adopted into the project: ⟨STAT⟩": "已并入主项目：⟨STAT⟩",
        "No changes to adopt.": "该分身没有改动",
        "Applying…": "并入中…",
        "PICK HUNKS…": "选择采纳…",
        "Choose files and hunks to adopt from this worktree": "从这个分身按文件/改动块挑选要并入的内容",
        "PICK HUNKS TO ADOPT": "按块选择采纳",
        "⟨HUNKS⟩ hunk(s) / ⟨FILES⟩ file(s) selected": "已选 ⟨HUNKS⟩ 个改动块 / ⟨FILES⟩ 个文件",
        "ADOPT SELECTED": "采纳所选",
        "Apply only the checked hunks onto the project": "只把勾选的改动块并入主项目",
        "binary — not adoptable via patch": "二进制——不支持补丁采纳",
        "metadata only": "仅元数据变更",
        "Adopted ⟨HUNKS⟩ hunk(s) across ⟨FILES⟩ file(s).": "已并入 ⟨HUNKS⟩ 个改动块（⟨FILES⟩ 个文件）",
        "confidence: ⟨LEVEL⟩": "把握：⟨LEVEL⟩",
        "RATIONALE": "裁决理由",
        "Task lifecycle hooks": "任务生命周期钩子",
        "Run a local command when a background task completes, fails, or waits for you. Task facts arrive as RELAY_TASK_* environment variables; hooks fire while the GUI is running.":
            "后台任务完成、失败或等待你时执行本地命令。任务信息只经 RELAY_TASK_* 环境变量传入；钩子在 GUI 运行期间生效",
        "ADD HOOK": "新增钩子",
        "SAVE HOOK": "保存钩子",
        "Any agent": "任意智能体",
        "hook · completed": "完成时",
        "hook · failed": "失败时",
        "hook · waiting": "等待时",
        "Command run with /bin/zsh -c (task facts come via RELAY_TASK_* env)": "经 /bin/zsh -c 执行的命令（任务信息经 RELAY_TASK_* 环境变量传入）",
        "Hook command must be 1–1000 bytes": "钩子命令须为 1–1000 字节",
        "PROJECTS": "项目",
        "Add project…": "添加项目…",
        "Remove from sidebar": "从侧边栏移除",
        "Use as current project": "设为当前项目",
        "PROJECT HISTORY": "项目历史",
        "Search project history": "搜索项目历史",
        "All work saved under each project": "按项目归档的全部工作记录",
        "No project history yet.": "还没有项目历史",
        "No history matches this search.": "没有匹配这次搜索的历史记录",
        "History stays on this Mac · open any item to continue": "历史保存在这台 Mac 上 · 打开任意记录即可继续",
        "SESSION LIBRARY": "会话库",
        "… all ⟨N⟩ sessions": "… 全部 ⟨N⟩ 条",
        "Search, rename or delete sessions": "搜索、改名或删除会话",
        "Open this thread as a floating window": "把这条线程开成浮动窗口",
        "Thread": "线程",
        "SESSIONS": "会话",
        "What the daemon already records — terminals stay unrecorded": "daemon 自动记录的一切——嵌入式终端仍不记录",
        "Browse and reopen everything the daemon has recorded": "浏览并重开 daemon 记录的全部会话",
        "Close session library": "关闭会话库",
        "Search title, prompt, agent, project or ID": "搜索标题、提示词、智能体、项目或 ID",
        "ALL": "全部",
        "SINGLE TASKS": "单任务",
        "OPEN AS WINDOW": "开成窗口",
        "Re-mount this daemon group as a floating window": "把这个 daemon 任务组重新挂载为浮动窗口",
        "VIEW": "查看",
        "HIDE": "收起",
        "Session title": "会话标题",
        "⟨N⟩ turn(s)": "⟨N⟩ 轮",
        "Continue this thread with a new message…": "输入新消息继续这条线程…",
        "This task has no resumable session.": "该任务没有可续会话",
        "REFRESH": "刷新",
        "DELETE SESSION": "删除会话记录",
        "Removes the daemon record permanently; running tasks are not deleted.": "永久移除 daemon 里的这条记录；运行中的任务不可删除",
        "Stop or wait for the running task first": "先停止或等待运行中的任务",
        "No sessions yet — dialogue, compare, chain and quick-bar tasks appear here automatically.": "还没有会话——对话、对比、串联与快速条任务会自动出现在这里",
        "No sessions match this search.": "没有匹配这次搜索的会话",
        "Records live in the local daemon · rename anytime · delete asks first": "记录存于本机 daemon · 随时改名 · 删除前确认",
        "CODE BASELINE": "代码基线",
        "dirty at save": "保存时有未提交改动",
        "clean at save": "保存时干净",
        "CHECK DRIFT": "检查漂移",
        "HEAD unchanged": "HEAD 未变",
        "HEAD unchanged · uncommitted changes present": "HEAD 未变 · 当前有未提交改动",
        "HEAD moved to ⟨COMMIT⟩": "HEAD 已前进至 ⟨COMMIT⟩",
        "repository unavailable": "仓库不可用",
        "Compare the stored baseline with the repository's current HEAD — read-only": "把保存的基线与仓库当前 HEAD 做只读比较",
        "FORK": "分叉",
        "Branch this chain into a new window; forkable steps continue a copy of their session, the original stays untouched":
            "把这条串联分叉到新窗口——支持分叉的步骤续接会话副本，原窗口与原会话不动",
        "⑂ Forked — every step continues a copy of its session.": "⑂ 已分叉——每一步都续接自己的会话副本",
        "⑂ Forked — no step supports session forking; all start fresh.": "⑂ 已分叉——各步骤均不支持会话分叉，全部重新开始",
        "⑂ Forked — ⟨FORKED⟩ step(s) continue copied sessions, ⟨FRESH⟩ start fresh.":
            "⑂ 已分叉——⟨FORKED⟩ 步续接会话副本，⟨FRESH⟩ 步重新开始",
        "Seat presets": "座次预设",
        "Named personas — an agent plus option overrides and extra rules. Pick them as members in dialogues and comparisons.":
            "命名人格档案——智能体 + 选项覆盖 + 追加规则；可在圆桌与同时发送里作为成员选用",
        "ADD PRESET": "新增预设",
        "Preset name": "预设名称",
        "Agent": "智能体",
        "(default)": "（默认）",
        "Extra rules prepended to this seat's prompts (optional)": "追加规则，会作为可见文本前置到该座次的提示词（可选）",
        "SAVE PRESET": "保存预设",
        "rules": "规则",
        "Preset name must be 1–48 bytes on a single line": "预设名称须为单行 1–48 字节",
        "Preset rules must stay within 4000 bytes": "预设规则不能超过 4000 字节",
        "Pick an agent for this preset": "请为预设选择一个智能体",
        "Self-check before delivering": "自检后交付",
        "Appends a visible verification instruction to the prompt": "在提示词末尾附加一段可见的自验证指令",
        "After finishing, run a self-check: verify each requirement above is met, actually test what can be tested, fix anything you find before delivering, and end with one line stating the self-check result.":
            "完成主要任务后进行一轮自检：逐条核对上述要求是否全部满足；能实际验证的改动或结论要实际验证；发现问题先修正再交付；最后用一行说明自检结果。",
        "ALWAYS": "总是",
        "Auto-⟨ACTION⟩ when the command starts with '⟨PREFIX⟩'":
            "命令以「⟨PREFIX⟩」开头时自动「⟨ACTION⟩」",
        "AUTO RULES": "自动规则",
        "Rules apply per agent to matching tool approvals — remove anytime.":
            "规则按智能体生效，匹配的工具审批自动处理；可随时删除",
        "Remove this rule": "删除这条规则",
        "Save a rule so matching approvals are answered automatically.":
            "保存规则：以后同类审批自动应答，不再打扰",
        "no changes yet": "还没动手…",
        "Queue the next message — sent automatically when this round finishes…":
            "排队下一条：本轮结束后自动发出…",
        "⟨N⟩ queued": "已排队 ⟨N⟩",
        "Clear queue": "点击清空排队",
        "EVIDENCE TIMELINE": "证据时间线",
        "CHECKPOINT": "检查点",
        "ACTIONS": "行动",
        "RECOVERIES": "恢复",
        "WITNESSES": "见证",
        "TILE": "平铺",
        "Arrange all terminals in a grid": "一键把全部终端平铺排列",
        "Arrange all windows in a grid": "一键把全部窗口平铺排列",
        "WINDOWS": "窗口",
        "RESTORE": "恢复",
        "Restore the previous CLI desk": "恢复上次 CLI 桌面",
        "DESK MEMORY": "桌面记忆",
        "⟨N⟩ CLI windows · layout and folders remembered":
            "⟨N⟩ 个 CLI 窗口 · 已记住布局与目录",
        "RESTORE DESK": "恢复桌面",
        "FORGET": "忘记",
        "Desk restored.": "已恢复上次 CLI 桌面",
        "Some saved terminals are unavailable.": "已恢复可用终端；部分 CLI 当前不可用",
        "Saved terminals are unavailable.": "已保存的 CLI 当前都不可用",
        "Start a meeting with this agent": "以它为一方，开一场智能体会议",
        "Open its CLI terminal": "点击整行打开它的 CLI 终端",
        "Send one prompt to several agents": "同一段提示词并行发给多个智能体",
        "Relay the answer through steps": "答案按步骤顺序接力传递",
        "Meeting": "会议",
        "AGENT DIALOGUE": "智能体对话",
        "Open a meeting between two agents": "打开一个双智能体会议窗口，让它们相互交谈",
        "Close dialogue": "关闭对话",
        "Dialogue limit reached (2)": "最多同时 2 个对话",
        "Dialogue topic": "对话主题",
        "What should they discuss?": "想让它们讨论什么？",
        "Rounds per agent": "每方轮数",
        "START": "开始",
        "STOP": "停止",
        "+1 ROUND": "+1 轮",
        "Each side keeps its own session; replies relay automatically.":
            "双方各自保持会话记忆，回复由 Relay 自动接力。",
        "Pick two agents and a topic": "选择两个智能体并输入主题",
        "⟨NAME⟩ is replying…": "⟨NAME⟩ 回答中…",
        "Dialogue completed": "对话完成",
        "Stopped": "已停止",
        "Failed:": "失败：",
        "You are in a multi-round dialogue with another AI agent (⟨OTHER⟩).":
            "你正在与另一个 AI 智能体（⟨OTHER⟩）进行多轮对话。",
        "Topic:": "主题：",
        "The other agent (⟨OTHER⟩) said:": "对方（⟨OTHER⟩）说：",
        "Give your opening view in plain text, concise.":
            "请直接以纯文字给出你的开场观点，简明扼要。",
        "Reply directly and continue the dialogue in plain text.":
            "请直接以纯文字回应，继续这场对话。",
        "This is your final turn — wrap up.": "这是你的最后一轮，请收尾总结。",
        "You may use tools, including web search. Treat local files and content as read-only; do not modify them.":
            "可以使用工具，包括网络检索。本地文件与内容仅限读取，不要修改。",
        "The agent returned no text answer.": "对方没有返回文字回答。",
        "The turn failed.": "该轮执行失败。",
        "LINK": "串联",
        "Dialogue, parallel send, or chained relay": "对话 / 同时发送 / 顺序串联",
        "SEND TO SEVERAL AGENTS AT ONCE": "同时发给多个智能体",
        "RELAY THE ANSWER THROUGH STEPS": "答案按步骤顺序接力",
        "Compare limit reached (2)": "最多同时 2 个对比",
        "Chain limit reached (2)": "最多同时 2 条串联",
        "Prompt sent to every selected agent": "发给每个选中智能体的同一段提示词",
        "Pick 2–4 agents": "选择 2–4 个智能体",
        "Pick agents and a prompt": "选择智能体并输入提示词",
        "Running in parallel…": "并行执行中…",
        "All members finished": "全部成员已结束",
        "Approvals": "审批",
        "No pending approvals.": "没有待处理的审批。",
        "Tasks that ask for tool approval or extra input show up here.":
            "任务请求工具审批或补充输入时会出现在这里。",
        "Waiting for approval — respond in the approvals window.":
            "等待审批——请在审批窗口处理。",
        "Close approvals": "关闭审批窗口",
        "⟨N⟩ pending": "⟨N⟩ 项待处理",
        "STEP": "步骤",
        "Order the steps and enter a prompt": "编排步骤顺序并输入提示词",
        "Relaying step by step…": "逐步接力中…",
        "Chain completed": "串联完成",
        "Add steps in execution order": "按执行顺序添加步骤",
        "Prompt for the first step": "发给第一步的提示词",
        "2–4 steps; runs in the daemon, survives closing the GUI":
            "2–4 步；由 daemon 执行，关闭 GUI 也会继续",
        "MIX has no standalone CLI to embed.": "MIX 没有可嵌入的独立 CLI。",
        "This agent's CLI was not found.": "未找到该智能体的 CLI。",
        "EXITED": "已退出",
        "RESTART": "重启",
        "Close terminal": "关闭终端",
        "Pin this thread as a side pane": "把这条线程钉为右侧并排窗格",
        "Close this pane": "关闭该窗格",
        "Continue this thread…": "继续这条线程…",
        "This thread has no resumable session.": "该线程没有可续聊的会话。",
        "Continue from this answer with another agent": "以这条答案为起点交给其他智能体继续",
        "Notify when a background task finishes, fails, or waits for your response.":
            "后台任务完成、失败或等待你响应时发送 macOS 通知。",
        "On": "开",
        "Off": "关",
        "Codex default mode": "Codex 默认模式",
        "Default runs directly. Plan allows Codex to ask questions before execution.": "“默认”直接执行；“计划”允许 Codex 在执行前提问。",
        "MIX default model": "MIX 默认模型",
        "The Codex model used when MIX combines Claude and Codex.": "MIX 组合 Claude 与 Codex 时使用的 Codex 模型。",
        "Reasoning effort": "推理强度",
        "Used by the selected Codex model inside MIX.": "应用于 MIX 内所选的 Codex 模型。",
        "Settings are saved automatically": "设置会自动保存",
        "Open Settings…": "打开设置…",
        "Open Relay": "打开 Relay",
        "Refresh Status": "刷新状态",
        "No active or waiting tasks": "没有运行中或等待中的任务",
        "Daemon continues after the UI quits": "退出界面后，后台任务仍会继续",
        "Quit Relay UI": "退出 Relay 界面",
        "background tasks": "后台任务",
        "ACTIVE": "进行中",
        "WAITING": "等待中",
        "AGENTS": "智能体",
        "MANAGE": "管理",
        "SETTINGS": "设置",
        "NEW THREAD": "新线程",
        "THREADS": "线程",
        "NO THREADS": "暂无线程",
        "Pick an agent": "选择智能体",
        "and enter a task": "并输入任务",
        "LOCAL ONLY": "仅限本机",
        "PARALLEL": "并行",
        "TEAMWORK": "分工合作",
        "UNDO": "撤销",
        "CLEAR": "清除",
        "ROUTE": "执行顺序",
        "click agents in execution order": "按执行顺序点击智能体",
        "Instruction passed between steps (optional)": "步骤间传递的指令（可选）",
        "Search title, agent, cwd": "搜索标题、智能体或工作目录",
        "PROJECT": "项目",
        "Delete this thread?": "删除这个线程？",
        "Its local history and output will be removed from Relay.": "Relay 中保存的本地历史与输出将被删除。",
        "Delete": "删除",
        "SAVE": "保存",
        "RENAME": "重命名",
        "EXPORT": "导出",
        "Export this thread as Markdown": "把这条线程导出为 Markdown 文件",
        "Copy this reply": "复制这条回答",
        "CANCEL": "取消",
        "DELETE": "删除",
        "CHOOSE": "选择",
        "Working directory": "工作目录",
        "MODEL": "模型",
        "EFFORT": "强度",
        "CODEX MODE": "CODEX 模式",
        "Interactive questions enabled": "允许交互提问",
        "Direct execution": "直接执行",
        "Local multi-CLI workspace": "本地多 CLI 工作台",
        "Thread title": "线程标题",
        "Waiting for adapter output…": "正在等待 Adapter 输出…",
        "RELAY READY": "RELAY 已就绪",
        "unavailable": "不可用",
        "Enter a task below. Relay stays active after this window closes.": "在下方输入任务。关闭窗口后 Relay 仍会继续运行。",
        "FOCUS": "聚焦",
        "Waiting in USER GATE — use FOCUS to respond": "正在等待用户操作，请聚焦后回答",
        "RETURN": "提交",
        "CONTINUE": "继续",
        "Custom response": "自定义回答",
        "SENDING…": "发送中…",
        "SEND RESPONSE": "发送回答",
        "APPROVAL": "审批",
        "INPUT": "输入",
        "ADAPTER MANIFESTS": "ADAPTER 配置",
        "ADD CLI": "添加 CLI",
        "IMPORT": "导入",
        "CLOSE": "关闭",
        "USER DIR": "用户目录",
        "REVEAL": "显示位置",
        "USER": "用户",
        "BUILT-IN": "内置",
        "EDIT": "编辑",
        "ADD LINE CLI": "添加行式 CLI",
        "EDIT LINE CLI": "编辑行式 CLI",
        "Prompt via stdin · output from stdout": "通过 stdin 输入 · 从 stdout 输出",
        "EXECUTABLE": "可执行文件",
        "ARGUMENTS · ONE ARGUMENT PER LINE · OPTIONAL": "参数 · 每行一个 · 可选",
        "LOCAL MANIFEST": "本地配置",
        "SAVING…": "保存中…",
        "CREATE ADAPTER": "创建 ADAPTER",
        "SAVE ADAPTER": "保存 ADAPTER",
        "Chinese": "简体中文",
        "Japanese": "日本語",
        "Manage adapter manifests": "管理 Adapter 配置",
        "Open Relay settings": "打开 Relay 设置",
        "Send one task to several agents in parallel": "将同一任务并行发送给多个智能体",
        "Pass each completed answer to the next agent": "将每一步完成的回答交给下一个智能体",
        "Clear thread search": "清除线程搜索",
        "Refresh threads": "刷新线程",
        "Cancel rename": "取消重命名",
        "Delete this local thread": "删除这个本地线程",
        "NO MATCHES": "没有匹配项",
        "Change the search": "请修改搜索条件",
        "No threads with this status": "没有此状态的线程",
        "CLEAR SEARCH": "清除搜索",
        "SHOW ALL": "显示全部",
        "Some output was truncated after reaching the local history limit.": "部分输出因达到本地历史上限而被截断。",
        "BACK TO CHAIN": "返回接力",
        "BACK TO COMPARE": "返回对比",
        "Focused on one chain step": "正在查看一个接力步骤",
        "Focused on one comparison member": "正在查看一个对比成员",
        "Open this chain step as a normal thread": "将这个接力步骤作为普通线程打开",
        "Open this member as a normal thread": "将这个成员作为普通线程打开",
        "Click at least two agents to build a chain…": "请至少点击两个智能体来创建接力…",
        "Check at least two agents to compare…": "请至少选择两个智能体进行对比…",
        "Respond in USER GATE above to continue…": "请在上方的用户操作区回答后继续…",
        "The selected task is still running…": "所选任务仍在运行…",
        "Continue this thread, or type @agent to hand it off…": "继续此线程，或输入 @agent 进行交接…",
        "Type @agent to hand off, or start a new task…": "输入 @agent 进行交接，或开始新任务…",
        "Remove adapter": "移除 Adapter",
        "Its manifest will be deleted from the user adapter directory.": "它的配置文件将从用户 Adapter 目录中删除。",
        "Create a line-based CLI adapter": "创建行式 CLI Adapter",
        "Copy a manifest into the user adapter directory": "将配置文件复制到用户 Adapter 目录",
        "Rescan manifests": "重新扫描配置文件",
        "CLI ID · start with a letter or number · then a-z, 0-9, - or _": "CLI ID · 以字母或数字开头 · 后续可用 a-z、0-9、- 或 _",
        "DISPLAY NAME": "显示名称",
        "Relay creates a local manifest and registers it immediately. This simple adapter does not resume CLI-native sessions; import a custom manifest for session or JSONL support.": "Relay 会创建本地配置并立即注册。这个简单 Adapter 不会恢复 CLI 原生会话；如需 session 或 JSONL 支持，请导入自定义配置。",
        "Relay keeps the CLI ID and updates this local manifest immediately. Running tasks keep their existing process; new tasks use the saved executable and arguments.": "Relay 会保留 CLI ID 并立即更新本地配置。运行中的任务保持现有进程；新任务使用保存后的可执行文件与参数。"
    ]

    private static let japanese: [String: String] = [
        "Settings": "設定",
        "General": "一般",
        "Agents": "エージェント",
        "Interface language": "表示言語",
        "Changes the language used by Relay. CLI output and agent replies stay unchanged.": "Relay の画面表示を切り替えます。CLI 出力とエージェントの回答は原文のままです。",
        "Default working directory": "デフォルトの作業フォルダ",
        "Used when creating a new thread. Existing threads keep their own working directory.": "新しいスレッドの作成時に使用します。既存のスレッドは元の作業フォルダを保持します。",
        "Choose…": "選択…",
        "RECENT PROJECTS": "最近のプロジェクト",
        "Choose project folder…": "プロジェクトフォルダを選択…",
        "Switch project": "プロジェクトを切り替え",
        "New windows use this project": "新しいウィンドウはこのプロジェクトを使用",
        "PAIR": "ペア",
        "Open Claude and Codex for this project": "このプロジェクトで Claude と Codex を同時に開く",
        "Claude and Codex must both be available.": "Claude と Codex の両方が必要です",
        "Not enough terminal slots for this project pair.": "このプロジェクトのペアを開く空きがありません",
        "OUTPUT": "出力",
        "REVIEW": "未読",
        "NEXT": "次へ",
        "BACK": "戻る",
        "CONTEXT RELAY": "コンテキストリレー",
        "CONTEXT FORK": "コンテキスト分岐",
        "Carry this screen into one native CLI": "現在の画面を別のネイティブ CLI へ引き継ぐ",
        "Carry this screen into one or more native CLIs": "現在の画面を 1 つ以上のネイティブ CLI へ分岐する",
        "LOCAL MEMORY · 48 KB MAX": "ローカルメモリ · 最大 48 KB",
        "FROM": "元",
        "TO": "先",
        "Relay current terminal screen to another CLI": "現在のターミナル画面を別の CLI へ引き継ぐ",
        "Fork current terminal screen into one or more CLIs": "現在のターミナル画面を 1 つ以上の CLI へ分岐する",
        "Open another terminal to receive this context.": "このコンテキストを受け取る別のターミナルを開いてください",
        "Finish the current prompt flow before relaying context.": "現在のプロンプトフローを完了してからコンテキストを引き継いでください",
        "No terminal text to relay.": "引き継げるターミナルテキストがありません",
        "Close and clear captured context": "閉じて取得したコンテキストを消去",
        "Confirm this target is at an input prompt, then select it": "対象 CLI が入力欄にいることを確認してから選択",
        "What should the next CLI do with this context?": "次の CLI にこのコンテキストで何をさせますか？",
        "CURRENT SCREEN SNAPSHOT · EDIT BEFORE FILLING": "現在の画面スナップショット · 入力前に編集",
        "Captured only when you opened this panel · no clipboard or disk": "このパネルを開いた時だけ取得 · クリップボードもディスクも不使用",
        "FILL TARGET · DOES NOT RUN": "対象に入力 · 実行しません",
        "FILL ⟨N⟩ TARGETS · DOES NOT RUN": "⟨N⟩ 件に入力 · 実行しません",
        "Close context relay before opening prompt stage": "コンテキストリレーを閉じてからプロンプト仮置きを開く",
        "Close context fork before opening prompt stage": "コンテキスト分岐を閉じてからプロンプト仮置きを開く",
        "Close result confluence before opening prompt stage": "結果コンフルエンスを閉じてからプロンプト仮置きを開く",
        "Receiving terminal output": "ターミナルが出力中",
        "Terminal output needs review": "このターミナルに未確認の出力があります",
        "Receiving terminal output, output needs review": "ターミナルが出力中で、未確認の出力があります",
        "Focus latest terminal output": "最新の出力ターミナルへ移動",
        "Review next terminal output": "未確認の出力がある次のターミナルを表示",
        "Next action: review a staged prompt · ⟨N⟩ pending · ⌥⌘J": "次の操作：仮置きプロンプトを確認 · 未処理 ⟨N⟩ 件 · ⌥⌘J",
        "Next action: review unseen output · ⟨N⟩ pending · ⌥⌘J": "次の操作：未確認の出力を表示 · 未処理 ⟨N⟩ 件 · ⌥⌘J",
        "Focus latest terminal output · ⌥⌘J": "最新の出力ターミナルへ移動 · ⌥⌘J",
        "Return to ⟨CLI⟩ · ⌥⌘K": "⟨CLI⟩ に戻る · ⌥⌘K",
        "PROMPT STAGE": "プロンプト仮置き",
        "Prepare once, fill several native CLIs": "一度書いて複数のネイティブ CLI に入力",
        "FILL ONLY · DOES NOT RUN": "入力のみ・実行しません",
        "Close prompt stage": "プロンプト仮置きを閉じる",
        "Fill this terminal without running": "このターミナルに入力して実行しない",
        "This CLI has not enabled safe paste yet": "この CLI は安全な貼り付けがまだ有効ではありません",
        "READY TO FILL": "入力可能",
        "NOT READY": "準備未完了",
        "Write once, then fill every selected CLI…": "一度書いて、選択したすべての CLI に入力…",
        "Only CLIs with safe paste enabled can be selected.": "安全な貼り付けが有効な CLI のみ選択できます。",
        "Confirm each CLI is at an input prompt before selecting it.": "各 CLI が入力欄にいることを確認してから手動で選択してください。",
        "Confirm this CLI is at an input prompt, then select it": "この CLI が入力欄にいることを確認してから選択",
        "SELECTED": "選択済み",
        "CONFIRM PROMPT": "入力欄を確認",
        "SAFE PASTE UNAVAILABLE": "安全な貼り付けは利用不可",
        "FILL": "入力",
        "Filled into ⟨N⟩ terminals · Return was not pressed": "⟨N⟩ 個のターミナルに入力済み · Return は押していません",
        "REVIEW TERMINALS": "ターミナルを確認",
        "Fill one prompt into several terminals without running it": "同じプロンプトを複数のターミナルに入力して実行しない",
        "Hide prompt review; progress is kept": "プロンプト確認を閉じる・進捗は保持されます",
        "Open completed prompt review": "完了したプロンプト確認を開く",
        "Resume prompt review · ⟨N⟩ left": "プロンプト確認を再開・残り ⟨N⟩",
        "PROMPT REVIEW": "プロンプト確認",
        "DECISION BRIEF REVIEW": "判定ブリーフ確認",
        "Check the filled CLI before you run it": "実行前に入力済み CLI を確認",
        "DECISION BRIEF · ⟨BYTES⟩ UTF-8 B · ⟨RESULT⟩": "判定ブリーフ・⟨BYTES⟩ UTF-8 バイト・⟨RESULT⟩",
        "FULL RESULT": "結果全文",
        "BACK TO DECISION": "判定へ戻る",
        "BACK TO CLI REVIEW": "CLI 確認へ戻る",
        "CAPTURE ACTION RECEIPT": "アクション受領票を固定",
        "VIEW ACTION RECEIPT": "アクション受領票を表示",
        "Open the unsaved in-memory action receipt": "未保存のメモリアクション受領票を開く",
        "Freeze the exact filled brief and current visible screen; this does not claim success": "入力済みブリーフと現在の表示画面を固定します・成功を示すものではありません",
        "Return to the checkpoint; filled text stays in the CLI": "チェックポイントへ戻る・入力済みテキストは CLI に残ります",
        "Check each native CLI in order": "各ネイティブ CLI を順番に確認",
        "RETURN NOT SENT": "RETURN は未送信",
        "RETURN NOT DETECTED": "RETURN は未検出",
        "RETURN ⏎ ⟨COUNT⟩ / ⟨TOTAL⟩": "RETURN 検出 ⏎ ⟨COUNT⟩ / ⟨TOTAL⟩",
        "Close review; filled text stays in the terminals": "確認を閉じる・入力済みテキストはターミナルに残ります",
        "Hide review; progress and filled text stay in place": "確認を閉じる・進捗と入力済みテキストは保持されます",
        "This terminal closed before review": "確認前にこのターミナルが閉じられました",
        "Reviewed; select to revisit this terminal": "確認済み・選択してもう一度表示",
        "Currently reviewing this terminal": "このターミナルを確認中",
        "Select this terminal to review it": "選択してこのターミナルを確認",
        "CLOSED": "閉じました",
        "CHECKED": "確認済み",
        "CURRENT": "確認中",
        "PENDING": "未確認",
        "ALL TARGETS CHECKED": "すべて確認済み",
        "REVIEW ENDED": "確認を終了",
        "Return was never sent. Run each CLI when you decide.": "Return は送信していません。実行は各 CLI で判断してください。",
        "Closed targets were not counted as checked. Return was never sent.": "閉じた対象は確認済みに含みません。Return は送信していません。",
        "REVIEWING ⟨CURRENT⟩ OF ⟨TOTAL⟩": "⟨CURRENT⟩ / ⟨TOTAL⟩ を確認中",
        "Prompt cleared from Relay. Check the terminal input line.": "プロンプトは Relay から消去済みです。ターミナルの入力行を確認してください。",
        "⟨CHECKED⟩ checked · ⟨CLOSED⟩ closed · Return not sent": "確認済み ⟨CHECKED⟩ · 閉じた対象 ⟨CLOSED⟩ · Return 未送信",
        "NEW PROMPT": "新しいプロンプト",
        "END REVIEW": "確認を終了",
        "End review; filled text stays in the terminals": "確認進捗を消去して終了・入力済みテキストはターミナルに残ります",
        "Prompt text cleared · Return remains yours": "本文は消去済み・Return はあなたが判断",
        "RESULT CONFLUENCE": "結果コンフルエンス",
        "⟨N⟩ CLI screens frozen at one explicit moment": "明示的な 1 回の取得で ⟨N⟩ 件の CLI 画面を固定",
        "LOCAL MEMORY · EXPLICIT SNAPSHOT": "ローカルメモリ・明示取得",
        "Close and clear collected screens": "集約した画面を閉じて消去",
        "LIVE CLI": "ライブ CLI",
        "CLI CLOSED": "CLI 終了",
        "Focus live CLI": "ライブ CLI を表示",
        "Captured together only when you clicked · no clipboard or disk": "クリックした時だけ同時取得・クリップボードやディスクには保存しません",
        "RECAPTURE": "再取得",
        "BACK TO REVIEW": "確認へ戻る",
        "CAPTURE CURRENT SCREENS": "現在の画面を集約",
        "Freeze reviewed CLI screens together for local comparison": "確認済み CLI の現在画面をまとめて固定し、ローカルで比較",
        "Finish checking every target before collecting screens.": "すべての対象を確認してから画面を集約してください。",
        "Keep at least two reviewed terminals open to collect screens.": "画面を集約するには、確認済みターミナルを 2 つ以上開いたままにしてください。",
        "Keep every collected terminal open to recapture screens.": "再取得するには、集約したすべてのターミナルを開いたままにしてください。",
        "RESULT ARBITRATION": "結果判定",
        "ARBITRATE RESULTS": "結果を判定",
        "Give one CLI every frozen screen": "固定した全画面を 1 つの CLI へ",
        "FROZEN RESULTS · FILL ONLY": "固定結果・入力のみ",
        "What should the deciding CLI do with these results?": "判定する CLI に何をさせますか？",
        "ARBITER": "判定先",
        "⟨N⟩ frozen sources · 64 KB max": "固定元 ⟨N⟩ 件・最大 64 KB",
        "PAYLOAD PREFLIGHT": "ペイロード事前確認",
        "FULL": "全文",
        "TAIL KEPT": "末尾を保持",
        "UTF-8 BYTES · NO TOKEN GUESS": "UTF-8 バイト・トークン推測なし",
        "Enter an instruction to preview exact local bytes": "判定指示を入力すると正確なローカルバイト数を確認できます",
        "ARBITRATION SOURCES": "判定元",
        "⟨N⟩ frozen screens behind this arbitration": "この判定に使った固定画面 ⟨N⟩ 件",
        "LOCAL MEMORY · READ ONLY": "ローカルメモリ・読み取り専用",
        "BACK TO ARBITER REVIEW": "判定先の確認に戻る",
        "VIEW ⟨N⟩ FROZEN SOURCES · ⟨BYTES⟩ B": "固定元 ⟨N⟩ 件を表示・⟨BYTES⟩ B",
        "View the exact frozen screens staged for this arbitration": "この判定に入力した固定画面を表示",
        "⟨N⟩ SOURCES · ⟨BYTES⟩ B STAGED": "入力済み ⟨N⟩ 件・⟨BYTES⟩ B",
        "CHECK LIVE DRIFT": "ライブ差分を確認",
        "UNCHANGED": "変更なし",
        "CHANGED": "変更あり",
        "Compare each frozen source with its live visible screen once": "各固定元を現在の表示画面と一度だけ比較",
        "DECISION SEAL": "判定記録",
        "Frozen sources → exact payload → arbiter result": "固定元 → 正確なペイロード → 判定結果",
        "EXPLICIT · LOCAL MEMORY · READ ONLY": "明示操作・ローカルメモリ・読み取り専用",
        "FROZEN SOURCES": "固定元",
        "EXACT PAYLOAD": "正確なペイロード",
        "UTF-8 BYTES": "UTF-8 バイト",
        "⟨N⟩ frozen sources": "固定元 ⟨N⟩ 件",
        "ARBITER RESULT": "判定結果",
        "SEALED": "固定済み",
        "Sealed only when you clicked · no clipboard or disk": "クリック時だけ固定・クリップボードやディスクには保存しません",
        "SEAL RESULT": "結果を固定",
        "VIEW SEALED RESULT": "固定結果を表示",
        "DECISIONS": "判定",
        "DECISION LIBRARY": "判定ライブラリ",
        "PRIVATE LOCAL FILES": "非公開ローカルファイル",
        "Close decision library": "判定ライブラリを閉じる",
        "SEARCH DECISIONS": "判定を検索",
        "Search agent, project, evidence, result or ID": "エージェント、プロジェクト、証拠、結果、ID を検索",
        "Search title, tag, agent, project, evidence, result or ID": "タイトル、タグ、エージェント、プロジェクト、証拠、結果、ID を検索",
        "Clear decision search": "判定検索をクリア",
        "No matching decisions": "一致する判定はありません",
        "PIN DECISION": "判定をピン留め",
        "UNPIN DECISION": "ピン留めを解除",
        "EDIT LABEL": "ラベルを編集",
        "CLOSE LABEL": "ラベルを閉じる",
        "PRIVATE DECISION LABEL": "非公開判定ラベル",
        "ACTION RECEIPTS · ⟨N⟩": "アクション受領票・⟨N⟩",
        "CURRENT SCREENS · NOT SUCCESS PROOF": "現在の画面・成功の証明ではありません",
        "Open this private action receipt": "この非公開アクション受領票を開く",
        "DECISION ACTION RECEIPT": "判定アクション受領票",
        "SAVED PRIVATE · 0600": "非公開保存済み・0600",
        "UNSAVED · LOCAL MEMORY": "未保存・ローカルメモリのみ",
        "DISCARD UNSAVED RECEIPT": "未保存の受領票を破棄",
        "DISCARD TO DECISION": "破棄して判定へ戻る",
        "The unsaved in-memory receipt will be discarded.": "未保存のメモリ内受領票を破棄します。",
        "SEALED DECISION": "固定済み判定",
        "USER RETURN DETECTED": "ユーザーの RETURN を検出",
        "RELAY DID NOT SEND IT": "RELAY は送信していません",
        "CURRENT SCREEN": "現在の画面",
        "EXACT FILLED DECISION BRIEF": "入力した判定ブリーフ全文",
        "TAIL KEPT · ⟨KEPT⟩ / ⟨TOTAL⟩ B": "末尾を保持・⟨KEPT⟩ / ⟨TOTAL⟩ バイト",
        "FULL SEALED RESULT": "固定済み結果全文",
        "CAPTURED CURRENT SCREEN": "固定した現在の画面",
        "VISIBLE AT CAPTURE TIME · NOT A SUCCESS CLAIM": "取得時の表示・成功を示すものではありません",
        "This receipt proves the captured chain only; it does not prove task completion or success.": "この受領票が示すのは固定した因果関係だけです。タスク完了や成功の証明ではありません。",
        "SAVE PRIVATE RECEIPT": "非公開受領票を保存",
        "RECOVER IN LIVE CLI": "ライブ CLI で復元",
        "RECEIPT → LIVE CLI RECOVERY": "受領票 → ライブ CLI 復元",
        "FROZEN EVIDENCE · FILL ONLY": "固定証拠・入力のみ",
        "FROZEN SCREEN": "固定画面",
        "Optional next instruction for the recovered CLI…": "復元先 CLI への任意の次の指示…",
        "Relay carries the exact receipt into one prompt-ready CLI and leaves Return to you.": "Relay は正確な受領票を入力待ちの CLI に入力し、Return はユーザーに委ねます。",
        "⟨KEPT⟩ / ⟨TOTAL⟩ B SCREEN": "画面保持 ⟨KEPT⟩ / ⟨TOTAL⟩ バイト",
        "Frozen receipt stays unchanged · no clipboard or disk": "固定受領票は変更しません・クリップボードやディスク不使用",
        "ACTION RECOVERY REVIEW": "アクション復元確認",
        "Check the recovered CLI before you run it": "実行前に復元先 CLI の入力内容を確認",
        "ACTION RECOVERY · ⟨BYTES⟩ UTF-8 B · ⟨SCREEN⟩": "アクション復元・⟨BYTES⟩ UTF-8 B・⟨SCREEN⟩",
        "BACK TO ACTION RECEIPT": "アクション受領票へ戻る",
        "Return to the frozen receipt; filled text stays in the CLI": "固定受領票へ戻ります。入力済みテキストは CLI に残ります",
        "RECOVERY CHANGES · ⟨N⟩": "復元変化・⟨N⟩",
        "VISIBLE SCREEN EVIDENCE · NOT SUCCESS PROOF": "表示画面の証拠・成功の証明ではありません",
        "Open this private recovery change": "この非公開の復元変化を開く",
        "RECOVERY CHANGE RECEIPT": "復元変化受領票",
        "DISCARD UNSAVED RECOVERY CHANGE": "未保存の復元変化を破棄",
        "DISCARD TO ACTION RECEIPT": "破棄してアクション受領票へ戻る",
        "The unsaved recovery screen will be discarded.": "未保存の復元画面を破棄します。",
        "BACK TO RECOVERY REVIEW": "復元確認へ戻る",
        "FROZEN RECEIPT SCREEN": "固定受領票画面",
        "RECOVERY SCREEN": "復元後の画面",
        "VISIBLE SCREEN CHANGE": "表示画面の変化",
        "SCREEN EVIDENCE · NOT SUCCESS PROOF": "画面証拠・成功の証明ではありません",
        "This receipt records a visible change only; it does not prove completion or success.": "この受領票は表示画面の変化だけを記録します。完了や成功の証明ではありません。",
        "SAVE PRIVATE RECOVERY CHANGE": "非公開の復元変化を保存",
        "VIEW RECOVERY CHANGE": "復元変化を表示",
        "Open the unsaved in-memory recovery screen comparison": "未保存のメモリ内復元画面比較を開く",
        "CAPTURE RECOVERY CHANGE": "復元変化を取得",
        "Compare the current visible screen with the frozen receipt; this does not claim success": "現在の表示画面と固定受領票を比較します。成功を示すものではありません",
        "CONTINUE CHANGE IN LIVE CLI": "復元変化をライブ CLI に引き継ぐ",
        "RECOVERY CHANGE → LIVE CLI": "復元変化 → ライブ CLI",
        "PRIVATE LINEAGE · FILL ONLY": "非公開系譜・入力のみ",
        "Optional instruction for the next CLI…": "次の CLI への任意の指示…",
        "Relay carries both recorded screens into one prompt-ready CLI and leaves Return to you.": "Relay は記録済みの2画面を入力待ちの CLI に入力し、Return はユーザーに委ねます。",
        "⟨FROZEN⟩ / ⟨FROZEN_TOTAL⟩ B FROZEN · ⟨RECOVERY⟩ / ⟨RECOVERY_TOTAL⟩ B RECOVERY": "固定画面保持 ⟨FROZEN⟩ / ⟨FROZEN_TOTAL⟩ B・復元画面保持 ⟨RECOVERY⟩ / ⟨RECOVERY_TOTAL⟩ B",
        "Saved change stays unchanged · no clipboard or disk": "保存済み変化は変更しません・クリップボードやディスク不使用",
        "RECOVERY CHANGE HANDOFF REVIEW": "復元変化引き継ぎ確認",
        "Check the relayed recovery change before you run it": "実行前に引き継いだ復元変化を確認",
        "RECOVERY HANDOFF · ⟨BYTES⟩ UTF-8 B · ⟨SCREENS⟩": "復元引き継ぎ・⟨BYTES⟩ UTF-8 B・⟨SCREENS⟩",
        "BOTH SCREENS FULL": "両画面全文",
        "SCREEN TAIL KEPT": "画面末尾を保持",
        "BACK TO RECOVERY CHANGE": "復元変化へ戻る",
        "Return to the saved recovery change; filled text stays in the CLI": "保存済みの復元変化へ戻ります。入力済みテキストは CLI に残ります",
        "Finish the current prompt flow before relaying a recovery change.": "現在のプロンプト処理を完了してから復元変化を引き継いでください。",
        "The recovery change handoff does not fit the local prompt limit.": "復元変化の引き継ぎがローカルプロンプト上限を超えています。",
        "Confirm one live target is at an input prompt before relaying the change.": "変化を引き継ぐ前に、入力待ちのライブ対象を1件確認してください。",
        "RECOVERY CHANGE WITNESS": "復元変化の確認記録",
        "DISCARD UNSAVED RECOVERY WITNESS": "未保存の復元変化確認を破棄",
        "DISCARD TO RECOVERY CHANGE": "破棄して復元変化へ戻る",
        "The unsaved witness screen and assessment will be discarded.": "未保存の確認画面と判断を破棄します。",
        "BACK TO WITNESS REVIEW": "確認先のレビューへ戻る",
        "RECOVERY CHANGE": "復元変化",
        "EXACT HANDOFF": "正確な引き継ぎ",
        "WITNESS SCREEN": "確認画面",
        "EXACT HANDOFF PAYLOAD": "正確な引き継ぎペイロード",
        "WITNESS VISIBLE SCREEN": "確認時の表示画面",
        "VIEW WITNESS SCREEN": "確認画面を表示",
        "VIEW EXACT HANDOFF": "正確な引き継ぎを表示",
        "YOUR WITNESS ASSESSMENT": "確認結果の判断",
        "SUPPORTS CHANGE": "変化を支持",
        "RAISES CONCERN": "懸念あり",
        "INCONCLUSIVE": "判断保留",
        "USER-LABELED · RELAY DOES NOT JUDGE": "ユーザー分類・RELAY は判定しません",
        "This witness records the exact handoff and visible review; it does not prove completion or correctness.": "この記録は正確な引き継ぎと表示された確認結果を保存します。完了や正しさの証明ではありません。",
        "SAVE PRIVATE WITNESS": "非公開の確認記録を保存",
        "RECOVERY WITNESSES · ⟨N⟩": "復元確認記録・⟨N⟩",
        "Open this private recovery witness": "この非公開の復元確認記録を開く",
        "VIEW RECOVERY WITNESS": "復元確認記録を表示",
        "Open the unsaved in-memory recovery witness": "未保存のメモリ内復元確認記録を開く",
        "CAPTURE RECOVERY WITNESS": "復元確認記録を取得",
        "Freeze the exact handoff and current witness screen; Relay does not judge it": "正確な引き継ぎと現在の確認画面を固定します。Relay は判定しません",
        "Return must be detected before capturing a recovery witness.": "ユーザーの Return を検出してから復元確認記録を取得してください。",
        "Keep the witness CLI open with a visible screen before capturing.": "確認先 CLI を開いたまま表示画面を確認してから取得してください。",
        "Recovery witness saved locally.": "復元確認記録をローカルに保存しました。",
        "Could not save the recovery witness.": "復元確認記録を保存できません。",
        "COMPARE WITNESSES": "確認記録を比較",
        "Compare two saved recovery witnesses without judging them": "保存済み復元確認記録を2件比較します。優劣は判定しません",
        "WITNESS COMPARISON": "確認記録の比較",
        "LEFT WITNESS": "左の確認記録",
        "RIGHT WITNESS": "右の確認記録",
        "SELECT TWO WITNESSES": "確認記録を2件選択",
        "Choose one saved witness for each side; the same record cannot occupy both sides.": "左右に保存済み記録を1件ずつ選択します。同じ記録は両側に選べません。",
        "SAME EXACT HANDOFF": "正確な引き継ぎは同一",
        "DIFFERENT EXACT HANDOFF": "正確な引き継ぎが相違",
        "USER LABELS MATCH": "ユーザー分類は一致",
        "USER LABELS DIFFER": "ユーザー分類が相違",
        "WITNESS SCREEN DIFFERENCE": "確認画面の差分",
        "LEFT WITNESS SCREEN": "左の確認画面",
        "RIGHT WITNESS SCREEN": "右の確認画面",
        "⟨PAYLOAD⟩ B HANDOFF · ⟨SCREEN⟩ B SCREEN": "引き継ぎ ⟨PAYLOAD⟩ B・画面 ⟨SCREEN⟩ B",
        "Both saved witnesses stay unchanged; Relay does not judge them.": "保存済み確認記録2件は変更しません。Relay は判定しません。",
        "4 FROZEN SOURCES · FILL ONLY": "4つの固定ソース・入力のみ",
        "PROMPT-READY TARGET": "入力待ちの対象",
        "Optional instruction for the comparison reviewer…": "比較を確認する CLI への任意の指示…",
        "Relay fills one comparison packet; it never runs the target or chooses a winner.": "Relay は比較パケット1件を入力するだけです。対象を実行せず、優劣も判定しません。",
        "LEFT HANDOFF": "左の引き継ぎ",
        "LEFT SCREEN": "左の画面",
        "RIGHT HANDOFF": "右の引き継ぎ",
        "RIGHT SCREEN": "右の画面",
        "MERGE": "集約",
        "UTF-8 B COMPARISON PACKET": "UTF-8 B 比較パケット",
        "Confirm one live target is at an input prompt before relaying witnesses.": "確認証拠を引き継ぐ前に、入力待ちのライブ対象を1件確認してください。",
        "SELECT": "選択",
        "Decision title": "判定タイトル",
        "Tags separated by commas": "タグをカンマ区切りで入力",
        "SAVE LABEL": "ラベルを保存",
        "Title and tags are stored separately; frozen evidence stays unchanged": "タイトルとタグは別ファイルに保存・固定証拠は変更しません",
        "8 TAGS MAX · 24 CHARACTERS EACH": "タグは最大 8 件・各 24 文字",
        "EVIDENCE READ ONLY · PRIVATE 0600": "証拠は読み取り専用・非公開 0600",
        "SAVE PRIVATE CHECKPOINT": "非公開チェックポイントを保存",
        "Writes this frozen chain to Relay Application Support": "この固定済み判定チェーンを Relay の Application Support に保存",
        "CHECKPOINT SAVED": "保存済み",
        "OPEN DECISION LIBRARY": "判定ライブラリを開く",
        "DECISION CHECKPOINT": "判定チェックポイント",
        "PRIVATE LOCAL FILE · 0600 · READ ONLY": "非公開ローカルファイル・0600・読み取り専用",
        "CHECKPOINT REPLAY": "チェックポイント再判定",
        "Frozen evidence reopened · parent stays unchanged": "固定証拠を再展開・親チェックポイントは変更しません",
        "PARENT CHECKPOINT · READ ONLY": "親チェックポイント・読み取り専用",
        "ARCHIVED SOURCE": "保存済みソース",
        "Parent checkpoint stays unchanged · no clipboard or disk": "親チェックポイントは変更しません・クリップボードやディスクには保存しません",
        "RE-ARBITRATE FROM CHECKPOINT": "チェックポイントから再判定",
        "Re-evaluate this frozen evidence with any live CLI": "この固定証拠を任意のライブ CLI で再評価",
        "CONTINUE FROM DECISION": "この判定から続行",
        "Carry this sealed result into one live CLI without running it": "固定結果を 1 つのライブ CLI に入力して実行しない",
        "DECISION → ACTION BRIDGE": "判定 → 実行ブリッジ",
        "LOCAL · FILL ONLY · DOES NOT RUN": "ローカル・入力のみ・実行しません",
        "SEALED RESULT": "固定結果",
        "UTF-8 B": "UTF-8 バイト",
        "Optional next instruction for the target CLI…": "対象 CLI への任意の次の指示…",
        "Relay adds checkpoint provenance, fills one prompt-ready CLI, and leaves Return to you.": "Relay がチェックポイント由来情報を添えて入力待ちの CLI に入力し、Return はユーザーに委ねます。",
        "⟨KEPT⟩ / ⟨TOTAL⟩ B RESULT": "結果 ⟨KEPT⟩ / ⟨TOTAL⟩ バイトを保持",
        "Select this prompt-ready CLI": "入力待ちのこの CLI を選択",
        "OPEN A TERMINAL TO CHOOSE A TARGET": "対象を選ぶにはターミナルを開いてください",
        "REOPEN ARBITRATION": "再判定を開く",
        "BACK TO CHECKPOINT": "チェックポイントへ戻る",
        "REPLAY DECISION": "再判定結果",
        "DERIVED CHECKPOINT · 0600": "派生チェックポイント・0600",
        "VIEW PARENT": "親チェックポイントを表示",
        "REPLAY": "再判定",
        "DECISION DELTA": "判定差分",
        "COMPARE RESULTS": "結果を比較",
        "Parent result ↔ derived result": "親結果 ↔ 派生結果",
        "Reference result ↔ current result": "参照結果 ↔ 現在の結果",
        "PARENT RESULT": "親結果",
        "DERIVED RESULT": "派生結果",
        "REFERENCE RESULT": "参照結果",
        "CURRENT RESULT": "現在の結果",
        "READ-ONLY FILES · LOCAL DIFF": "読み取り専用ファイル・ローカル差分",
        "+⟨ADDED⟩ added · −⟨REMOVED⟩ removed · =⟨UNCHANGED⟩ unchanged": "+⟨ADDED⟩ 追加・−⟨REMOVED⟩ 削除・=⟨UNCHANGED⟩ 変更なし",
        "EARLIER LINES OMITTED": "以前の行を省略",
        "LAST 64 KB · 300 LINES MAX": "末尾 64 KB・最大 300 行",
        "BACK TO DERIVED": "派生チェックポイントへ戻る",
        "Parent and derived checkpoints stay unchanged": "親と派生のチェックポイントは変更しません",
        "Compared checkpoints stay unchanged": "比較したチェックポイントは変更しません",
        "LINEAGE": "判定系譜",
        "ROOT": "ルート",
        "CURRENT NODE": "現在のノード",
        "CHILD": "派生",
        "PARENT MISSING": "親記録がありません",
        "CYCLE BLOCKED": "循環を遮断",
        "DEPTH LIMIT": "深さ上限に到達",
        "FAMILY LIMIT": "系譜上限に到達",
        "COMPARE LINEAGE": "系譜ノードを比較",
        "Compare any connected checkpoint": "同じ系譜内の任意のチェックポイントを比較",
        "Open checkpoint in lineage": "系譜内のチェックポイントを開く",
        "Finish the current prompt flow before replaying a checkpoint.": "現在のプロンプトフローを完了してからチェックポイントを再判定してください。",
        "Finish the current prompt flow before continuing from a decision.": "現在のプロンプトフローを完了してから判定の続きに進んでください。",
        "The decision brief does not fit the local prompt limit.": "判定ブリーフがローカルのプロンプト上限を超えています。",
        "Confirm one live target is at an input prompt before continuing.": "続行する前に、ライブの対象 CLI が入力欄にいることを確認してください。",
        "Saved checkpoint sources cannot be recaptured.": "保存済みチェックポイントのソースは再取得できません。",
        "MOVE TO TRASH": "ゴミ箱へ移動",
        "The checkpoint file can be recovered from Trash.": "チェックポイントファイルはゴミ箱から復元できます。",
        "BACK TO LIBRARY": "ライブラリへ戻る",
        "Explicit saves only · private files 0600 · deletion moves to Trash": "明示的な保存のみ・非公開ファイル 0600・削除はゴミ箱へ移動",
        "No saved decisions": "保存済みの判定はありません",
        "OPEN": "開く",
        "saved decision checkpoints were ignored": "件の保存済み判定チェックポイントを読み飛ばしました",
        "private decision files were ignored": "件の非公開判定ファイルを読み飛ばしました",
        "Decision checkpoint saved locally.": "判定チェックポイントをローカルに保存しました。",
        "Return must be detected before capturing an action receipt.": "ユーザーの Return を検出してからアクション受領票を固定してください。",
        "Keep the target open with a visible screen before capturing a receipt.": "対象 CLI を開いたまま表示画面を確認してから受領票を固定してください。",
        "Action receipt saved locally.": "アクション受領票をローカルに保存しました。",
        "Could not save the action receipt.": "アクション受領票を保存できません。",
        "Finish the current prompt flow before recovering from a receipt.": "現在のプロンプトフローを完了してから受領票を復元してください。",
        "The action recovery brief does not fit the local prompt limit.": "アクション復元ブリーフがローカルのプロンプト上限を超えています。",
        "Confirm one live target is at an input prompt before recovering.": "復元する前に、ライブの対象 CLI が入力欄にいることを確認してください。",
        "Return must be detected before capturing a recovery change.": "ユーザーの Return を検出してから復元変化を取得してください。",
        "Keep the recovery target open with a visible screen before capturing.": "復元先 CLI を開いたまま表示画面を確認してから変化を取得してください。",
        "Recovery change saved locally.": "復元変化をローカルに保存しました。",
        "Could not save the recovery change.": "復元変化を保存できません。",
        "Decision label is too long.": "判定タイトルまたはタグが上限を超えています。",
        "Decision label saved locally.": "判定ラベルをローカルに保存しました。",
        "Could not save the decision label.": "判定ラベルを保存できません。",
        "Could not save the decision checkpoint.": "判定チェックポイントを保存できません。",
        "Could not load saved decision checkpoints.": "保存済みの判定チェックポイントを読み込めません。",
        "Could not move the decision checkpoint to Trash.": "判定チェックポイントをゴミ箱へ移動できません。",
        "Open the frozen arbiter result": "固定した判定結果を表示",
        "Freeze the arbiter's current visible screen into this decision chain": "判定 CLI の現在の表示画面をこの判定記録に固定",
        "Finish checking the arbiter before sealing its result.": "判定先を確認してから結果を固定してください。",
        "Keep the reviewed arbiter open to seal its result.": "確認済みの判定先を開いたまま結果を固定してください。",
        "FILL ARBITER · DOES NOT RUN": "判定先に入力・実行しません",
        "Give frozen results to one CLI without running them": "固定した結果を 1 つの CLI に入力して実行しない",
        "Write an arbitration instruction that fits the local prompt limit.": "ローカルのプロンプト上限に収まる判定指示を入力してください。",
        "Confirm one live target is at an input prompt before relaying results.": "結果を入力する前に、ライブの対象 CLI が入力欄にいることを確認してください。",
        "⟨N⟩ left": "残り ⟨N⟩",
        "CHECKED · NEXT": "確認済み・次へ",
        "No edit key or Return detected": "編集入力も Return も検出していません",
        "Edit input detected; Return not detected": "編集入力を検出・Return は未検出",
        "Return detected; Relay did not send it": "ユーザーの Return を検出・Relay は送信していません",
        "Terminal restarted after the prompt was filled": "プロンプト入力後にターミナルが再起動しました",
        "Terminal closed after the prompt was filled": "プロンプト入力後にターミナルが閉じられました",
        "⟨COUNT⟩ targets closed or restarted after filling · ⏎ ⟨RETURN⟩": "入力後に ⟨COUNT⟩ 件が終了または再起動・⏎ ⟨RETURN⟩",
        "Return detected in ⟨COUNT⟩ of ⟨TOTAL⟩ terminals. Relay did not send it.": "⟨TOTAL⟩ 件中 ⟨COUNT⟩ 件でユーザーの Return を検出しました。Relay は送信していません。",
        "No Return detected. Run each CLI when you decide.": "Return は検出していません。実行は各 CLI で判断してください。",
        "⟨CHECKED⟩ checked · ⏎ ⟨RETURN⟩ · ⟨ISSUES⟩ interrupted": "確認済み ⟨CHECKED⟩・⏎ ⟨RETURN⟩・影響あり ⟨ISSUES⟩",
        "System notifications": "システム通知",
        "Quick input bar": "クイック入力バー",
        "Press Option-Space anywhere to send a task to the background daemon.":
            "どのアプリでも ⌥スペース で呼び出し、バックグラウンドの daemon にタスクを送れます。",
        "Send a task without leaving your app…": "アプリを離れずにタスクを送信…",
        "Runs in the background — you'll get a notification.": "バックグラウンドで実行され、完了時に通知が届きます。",
        "Switch agent (Tab)": "エージェント切替（Tab）",
        "TEMPLATES": "テンプレート",
        "SAVE AS TEMPLATE": "テンプレートとして保存",
        "Delete template": "テンプレートを削除",
        "Save this route as a template": "このルートをテンプレートとして保存",
        "Template name": "テンプレート名",
        "Cancel": "キャンセル",
        "Daemon log": "daemon ログ",
        "relayd writes diagnostics to a local log file inside Application Support.":
            "relayd の診断情報は Application Support 内のローカルログに書き込まれます。",
        "Open log": "ログを開く",
        "Close (Esc)": "閉じる（Esc）",
        "SPLIT": "分割",
        "TERMINALS": "ターミナル",
        "NO TERMINALS": "ターミナルなし",
        "Click an agent on the left": "左のエージェントをクリックして",
        "to open its real CLI here": "ここに本物の CLI を開く",
        "Terminal limit reached (4)": "ターミナルは同時に 4 つまで",
        "Drag to move": "タイトルバーをドラッグして移動、ダブルクリックで最大化",
        "Toggle maximize": "最大化 / 元に戻す",
        "Freeze these answers and pick one CLI to arbitrate them":
            "これらの回答を凍結し、合流パネルで仲裁 CLI を選択（決定ライブラリへ保存可）",
        "Need at least two non-empty results to arbitrate.": "仲裁には空でない結果が 2 つ以上必要です。",
        "Remount daemon compare/chain groups as windows": "daemon の比較/チェーン グループをウィンドウとして再マウント",
        "No arbiter yet — open an agent's CLI terminal from the left sidebar and let it reach its input prompt.": "審判がいません——左のサイドバーからエージェントの CLI ターミナルを開き、入力プロンプトで待機させてください",
        "Continue the relay with a new message…": "新しい指示でリレーを続行…",
        "SEND": "送信",
        "A step has no resumable session — follow-up rounds are unavailable.":
            "再開できないセッションのステップがあるため、追加ラウンドは利用できません。",
        "You are in a multi-round roundtable with other AI agents (⟨OTHERS⟩).":
            "あなたは他の AI エージェント（⟨OTHERS⟩）と複数ラウンドの円卓対話をしています。",
        "Since your last turn, the others said:": "あなたの前回の発言以降、他の参加者の発言：",
        "PARTICIPANT": "参加者",
        "Pick 2–4 agents and a topic": "エージェント 2〜4 とテーマを選択",
        "Add 2–4 participants in speaking order": "発言順に参加者を 2〜4 追加",
        "Everyone keeps their own session; turns go around the table.":
            "各参加者がセッションを保持し、発言は順番に回ります。",
        "FORK TO TERMINALS": "ターミナルへフォーク",
        "Fill these answers into live CLI terminals":
            "これらの回答を稼働中の CLI ターミナルへ填入します（実行はしません）",
        "Minimize to the dock": "下部ドックへ最小化",
        "Restore this window": "このウィンドウを復元",
        "ONE-CLICK VERDICT": "ワンクリック判定",
        "⟨NAME⟩ is arbitrating — structured verdict, no terminal needed…":
            "⟨NAME⟩ が判定中——構造化された結論、ターミナル不要…",
        "Pick an agent to judge these results headlessly; the verdict comes back structured and sealable.":
            "エージェントを選んでヘッドレスで判定。結論は構造化され、保存できます",
        "no terminal · no Return": "ターミナル不要 · Return 不要",
        "Moderator": "司会",
        "Speak as the moderator — starts one more round…":
            "司会として発言：全参加者に共有され、もう 1 ラウンド始まります…",
        "Roundtable minutes": "円卓議事録",
        "Transcript": "トランスクリプト",
        "Save the transcript as a Markdown file": "トランスクリプトを Markdown として保存",
        "⟨N⟩ approvals waiting — click to respond": "承認待ち ⟨N⟩ 件——クリックで対応",
        "Collapse sidebar": "サイドバーを畳む（⌘\\）",
        "Expand sidebar": "サイドバーを展開（⌘\\）",
        "Isolated worktrees (git)": "ワークツリー分離（git）",
        "Each agent codes in its own copy of the repo; adopt the winning diff afterwards.":
            "各エージェントが独立した作業コピーで実装し、勝者の差分を後から採用できます",
        "The current project is not a git repository — worktree isolation is unavailable.":
            "現在のプロジェクトは git リポジトリではないため、分離できません",
        "Isolated worktree: ⟨PATH⟩": "分離ワークツリー：⟨PATH⟩",
        "ADOPT THIS VERSION": "この版を採用",
        "Apply this worktree's diff onto the project": "このワークツリーの差分をプロジェクトへ適用",
        "Adopted into the project: ⟨STAT⟩": "プロジェクトへ適用しました：⟨STAT⟩",
        "No changes to adopt.": "変更はありません",
        "Applying…": "適用中…",
        "PICK HUNKS…": "選んで採用…",
        "Choose files and hunks to adopt from this worktree": "このワークツリーから採用するファイル/ハンクを選ぶ",
        "PICK HUNKS TO ADOPT": "ハンク単位で採用",
        "⟨HUNKS⟩ hunk(s) / ⟨FILES⟩ file(s) selected": "⟨HUNKS⟩ ハンク / ⟨FILES⟩ ファイル選択中",
        "ADOPT SELECTED": "選択分を採用",
        "Apply only the checked hunks onto the project": "チェックしたハンクだけをプロジェクトへ適用",
        "binary — not adoptable via patch": "バイナリ — パッチ採用不可",
        "metadata only": "メタデータのみ",
        "Adopted ⟨HUNKS⟩ hunk(s) across ⟨FILES⟩ file(s).": "⟨HUNKS⟩ ハンク（⟨FILES⟩ ファイル）を採用しました",
        "confidence: ⟨LEVEL⟩": "確度：⟨LEVEL⟩",
        "RATIONALE": "裁定理由",
        "Task lifecycle hooks": "タスクライフサイクルフック",
        "Run a local command when a background task completes, fails, or waits for you. Task facts arrive as RELAY_TASK_* environment variables; hooks fire while the GUI is running.":
            "バックグラウンドタスクの完了・失敗・待機時にローカルコマンドを実行。タスク情報は RELAY_TASK_* 環境変数で渡され、GUI 起動中に発火します",
        "ADD HOOK": "フック追加",
        "SAVE HOOK": "フック保存",
        "Any agent": "全エージェント",
        "hook · completed": "完了時",
        "hook · failed": "失敗時",
        "hook · waiting": "待機時",
        "Command run with /bin/zsh -c (task facts come via RELAY_TASK_* env)": "/bin/zsh -c で実行するコマンド（タスク情報は RELAY_TASK_* 環境変数）",
        "Hook command must be 1–1000 bytes": "フックコマンドは1〜1000バイトで指定してください",
        "PROJECTS": "プロジェクト",
        "Add project…": "プロジェクトを追加…",
        "Remove from sidebar": "サイドバーから削除",
        "Use as current project": "現在のプロジェクトにする",
        "PROJECT HISTORY": "プロジェクト履歴",
        "Search project history": "プロジェクト履歴を検索",
        "All work saved under each project": "プロジェクト別に保存されたすべての作業履歴",
        "No project history yet.": "プロジェクト履歴はまだありません",
        "No history matches this search.": "検索に一致する履歴はありません",
        "History stays on this Mac · open any item to continue": "履歴はこの Mac に保存 · 項目を開いて続行",
        "SESSION LIBRARY": "セッションライブラリ",
        "… all ⟨N⟩ sessions": "… 全 ⟨N⟩ 件",
        "Search, rename or delete sessions": "セッションを検索・改名・削除",
        "Open this thread as a floating window": "このスレッドをフローティングウィンドウで開く",
        "Thread": "スレッド",
        "SESSIONS": "セッション",
        "What the daemon already records — terminals stay unrecorded": "daemon が自動記録するすべて——組込ターミナルは記録されません",
        "Browse and reopen everything the daemon has recorded": "daemon の全記録を閲覧・再開",
        "Close session library": "セッションライブラリを閉じる",
        "Search title, prompt, agent, project or ID": "タイトル・プロンプト・エージェント・プロジェクト・IDで検索",
        "ALL": "すべて",
        "SINGLE TASKS": "単体タスク",
        "OPEN AS WINDOW": "ウィンドウで開く",
        "Re-mount this daemon group as a floating window": "この daemon グループをフローティングウィンドウとして再マウント",
        "VIEW": "表示",
        "HIDE": "閉じる",
        "Session title": "セッションタイトル",
        "⟨N⟩ turn(s)": "⟨N⟩ ターン",
        "Continue this thread with a new message…": "新しいメッセージでこのスレッドを続ける…",
        "This task has no resumable session.": "このタスクには再開可能なセッションがありません",
        "REFRESH": "更新",
        "DELETE SESSION": "セッション記録を削除",
        "Removes the daemon record permanently; running tasks are not deleted.": "daemon の記録を完全に削除します。実行中のタスクは削除できません",
        "Stop or wait for the running task first": "実行中のタスクを先に停止または完了させてください",
        "No sessions yet — dialogue, compare, chain and quick-bar tasks appear here automatically.": "まだセッションがありません——対話・比較・チェーン・クイックバーのタスクが自動的にここに現れます",
        "No sessions match this search.": "この検索に一致するセッションはありません",
        "Records live in the local daemon · rename anytime · delete asks first": "記録はローカル daemon 内 · いつでも改名可 · 削除前に確認",
        "CODE BASELINE": "コードベースライン",
        "dirty at save": "保存時に未コミット変更あり",
        "clean at save": "保存時クリーン",
        "CHECK DRIFT": "ドリフト確認",
        "HEAD unchanged": "HEAD 変化なし",
        "HEAD unchanged · uncommitted changes present": "HEAD 変化なし · 未コミット変更あり",
        "HEAD moved to ⟨COMMIT⟩": "HEAD は ⟨COMMIT⟩ に移動",
        "repository unavailable": "リポジトリ利用不可",
        "Compare the stored baseline with the repository's current HEAD — read-only": "保存済みベースラインと現在の HEAD を読み取り専用で比較",
        "FORK": "フォーク",
        "Branch this chain into a new window; forkable steps continue a copy of their session, the original stays untouched":
            "このチェーンを新しいウィンドウへ分岐します。対応ステップはセッションの複製を継続し、元は変わりません",
        "⑂ Forked — every step continues a copy of its session.": "⑂ フォーク済み——全ステップがセッション複製を継続",
        "⑂ Forked — no step supports session forking; all start fresh.": "⑂ フォーク済み——対応ステップなし、全て新規開始",
        "⑂ Forked — ⟨FORKED⟩ step(s) continue copied sessions, ⟨FRESH⟩ start fresh.":
            "⑂ フォーク済み——⟨FORKED⟩ ステップは複製を継続、⟨FRESH⟩ ステップは新規開始",
        "Seat presets": "シートプリセット",
        "Named personas — an agent plus option overrides and extra rules. Pick them as members in dialogues and comparisons.":
            "名前付きペルソナ——エージェント＋オプション上書き＋追加ルール。対話と比較のメンバーとして選べます",
        "ADD PRESET": "プリセット追加",
        "Preset name": "プリセット名",
        "Agent": "エージェント",
        "(default)": "（デフォルト）",
        "Extra rules prepended to this seat's prompts (optional)": "追加ルール。可視テキストとしてこの席のプロンプト冒頭に付加されます（任意）",
        "SAVE PRESET": "プリセット保存",
        "rules": "ルール",
        "Preset name must be 1–48 bytes on a single line": "プリセット名は1行・1〜48バイトで指定してください",
        "Preset rules must stay within 4000 bytes": "ルールは4000バイト以内にしてください",
        "Pick an agent for this preset": "プリセットのエージェントを選んでください",
        "Self-check before delivering": "セルフチェックして納品",
        "Appends a visible verification instruction to the prompt": "プロンプト末尾に可視の自己検証指示を追加します",
        "After finishing, run a self-check: verify each requirement above is met, actually test what can be tested, fix anything you find before delivering, and end with one line stating the self-check result.":
            "主要タスク完了後にセルフチェックを行うこと：上記要件を一つずつ確認し、検証できるものは実際に検証し、問題があれば修正してから納品し、最後に結果を一行で報告すること。",
        "ALWAYS": "常に",
        "Auto-⟨ACTION⟩ when the command starts with '⟨PREFIX⟩'":
            "コマンドが「⟨PREFIX⟩」で始まるとき自動で「⟨ACTION⟩」",
        "AUTO RULES": "自動ルール",
        "Rules apply per agent to matching tool approvals — remove anytime.":
            "ルールはエージェント単位で一致するツール承認を自動処理します。いつでも削除可能",
        "Remove this rule": "このルールを削除",
        "Save a rule so matching approvals are answered automatically.":
            "ルールを保存すると、同種の承認は自動で応答されます",
        "no changes yet": "まだ変更なし…",
        "Queue the next message — sent automatically when this round finishes…":
            "次のメッセージを予約：このラウンド終了後に自動送信…",
        "⟨N⟩ queued": "予約 ⟨N⟩",
        "Clear queue": "クリックで予約をクリア",
        "EVIDENCE TIMELINE": "証拠タイムライン",
        "CHECKPOINT": "チェックポイント",
        "ACTIONS": "アクション",
        "RECOVERIES": "リカバリー",
        "WITNESSES": "証人",
        "TILE": "整列",
        "Arrange all terminals in a grid": "すべてのターミナルをタイル状に整列",
        "Arrange all windows in a grid": "すべてのウィンドウをタイル状に整列",
        "WINDOWS": "ウィンドウ",
        "RESTORE": "復元",
        "Restore the previous CLI desk": "前回の CLI デスクを復元",
        "DESK MEMORY": "デスクメモリ",
        "⟨N⟩ CLI windows · layout and folders remembered":
            "CLI ウィンド ⟨N⟩ 個 · 配置とフォルダを記憶済み",
        "RESTORE DESK": "デスクを復元",
        "FORGET": "忘れる",
        "Desk restored.": "前回の CLI デスクを復元しました",
        "Some saved terminals are unavailable.": "利用可能なターミナルのみ復元しました",
        "Saved terminals are unavailable.": "保存された CLI は現在利用できません",
        "Start a meeting with this agent": "このエージェントを一方にして会議を開始",
        "Open its CLI terminal": "行をクリックで CLI ターミナルを開く",
        "Send one prompt to several agents": "同じプロンプトを複数エージェントへ並列送信",
        "Relay the answer through steps": "回答をステップ順にリレー",
        "Meeting": "会議",
        "AGENT DIALOGUE": "エージェント対話",
        "Open a meeting between two agents": "2 つのエージェントが話し合う会議ウィンドウを開く",
        "Close dialogue": "対話を閉じる",
        "Dialogue limit reached (2)": "対話は同時に 2 つまで",
        "Dialogue topic": "対話テーマ",
        "What should they discuss?": "何について話し合わせますか？",
        "Rounds per agent": "各エージェントのラウンド数",
        "START": "開始",
        "STOP": "停止",
        "+1 ROUND": "+1 ラウンド",
        "Each side keeps its own session; replies relay automatically.":
            "双方がそれぞれセッションを保持し、返信は Relay が自動で中継します。",
        "Pick two agents and a topic": "エージェント 2 つとテーマを選択",
        "⟨NAME⟩ is replying…": "⟨NAME⟩ が応答中…",
        "Dialogue completed": "対話完了",
        "Stopped": "停止済み",
        "Failed:": "失敗：",
        "You are in a multi-round dialogue with another AI agent (⟨OTHER⟩).":
            "あなたは別の AI エージェント（⟨OTHER⟩）と複数ラウンドの対話をしています。",
        "Topic:": "テーマ：",
        "The other agent (⟨OTHER⟩) said:": "相手（⟨OTHER⟩）の発言：",
        "Give your opening view in plain text, concise.":
            "プレーンテキストで簡潔に最初の見解を述べてください。",
        "Reply directly and continue the dialogue in plain text.":
            "プレーンテキストで直接応答し、対話を続けてください。",
        "This is your final turn — wrap up.": "これが最後のターンです。締めくくってください。",
        "You may use tools, including web search. Treat local files and content as read-only; do not modify them.":
            "ツール（Web 検索を含む）は使用できます。ローカルのファイルと内容は読み取り専用として扱い、変更しないでください。",
        "The agent returned no text answer.": "エージェントからテキストの回答がありませんでした。",
        "The turn failed.": "このターンは失敗しました。",
        "LINK": "リレー",
        "Dialogue, parallel send, or chained relay": "対話 / 同時送信 / 順次リレー",
        "SEND TO SEVERAL AGENTS AT ONCE": "複数のエージェントへ同時送信",
        "RELAY THE ANSWER THROUGH STEPS": "回答をステップ順にリレー",
        "Compare limit reached (2)": "比較は同時に 2 つまで",
        "Chain limit reached (2)": "チェーンは同時に 2 つまで",
        "Prompt sent to every selected agent": "選択した各エージェントへ送る同一プロンプト",
        "Pick 2–4 agents": "エージェントを 2〜4 つ選択",
        "Pick agents and a prompt": "エージェントとプロンプトを選択",
        "Running in parallel…": "並列実行中…",
        "All members finished": "全メンバーが終了しました",
        "Approvals": "承認",
        "No pending approvals.": "保留中の承認はありません。",
        "Tasks that ask for tool approval or extra input show up here.":
            "ツール承認や追加入力が必要なタスクはここに表示されます。",
        "Waiting for approval — respond in the approvals window.":
            "承認待ち——承認ウィンドウで対応してください。",
        "Close approvals": "承認ウィンドウを閉じる",
        "⟨N⟩ pending": "⟨N⟩ 件保留中",
        "STEP": "ステップ",
        "Order the steps and enter a prompt": "ステップを並べてプロンプトを入力",
        "Relaying step by step…": "ステップごとにリレー中…",
        "Chain completed": "チェーン完了",
        "Add steps in execution order": "実行順にステップを追加",
        "Prompt for the first step": "最初のステップへのプロンプト",
        "2–4 steps; runs in the daemon, survives closing the GUI":
            "2〜4 ステップ。daemon が実行し、GUI を閉じても継続します",
        "MIX has no standalone CLI to embed.": "MIX には埋め込める単体 CLI がありません。",
        "This agent's CLI was not found.": "このエージェントの CLI が見つかりません。",
        "EXITED": "終了",
        "RESTART": "再起動",
        "Close terminal": "ターミナルを閉じる",
        "Pin this thread as a side pane": "このスレッドを右側のペインとして固定",
        "Close this pane": "このペインを閉じる",
        "Continue this thread…": "このスレッドを続ける…",
        "This thread has no resumable session.": "このスレッドには再開できるセッションがありません。",
        "Continue from this answer with another agent": "この回答を起点に別のエージェントへ引き継ぐ",
        "Notify when a background task finishes, fails, or waits for your response.":
            "バックグラウンドのタスクが完了・失敗・応答待ちになったとき macOS 通知を送ります。",
        "On": "オン",
        "Off": "オフ",
        "Codex default mode": "Codex のデフォルトモード",
        "Default runs directly. Plan allows Codex to ask questions before execution.": "「デフォルト」は直接実行し、「計画」は実行前の質問を許可します。",
        "MIX default model": "MIX のデフォルトモデル",
        "The Codex model used when MIX combines Claude and Codex.": "MIX が Claude と Codex を組み合わせる際に使用する Codex モデルです。",
        "Reasoning effort": "推論強度",
        "Used by the selected Codex model inside MIX.": "MIX 内で選択した Codex モデルに適用します。",
        "Settings are saved automatically": "設定は自動的に保存されます",
        "Open Settings…": "設定を開く…",
        "Open Relay": "Relay を開く",
        "Refresh Status": "状態を更新",
        "No active or waiting tasks": "実行中または待機中のタスクはありません",
        "Daemon continues after the UI quits": "画面を終了してもバックグラウンド処理は継続します",
        "Quit Relay UI": "Relay の画面を終了",
        "background tasks": "バックグラウンドタスク",
        "ACTIVE": "実行中",
        "WAITING": "待機中",
        "AGENTS": "エージェント",
        "MANAGE": "管理",
        "SETTINGS": "設定",
        "NEW THREAD": "新規スレッド",
        "THREADS": "スレッド",
        "NO THREADS": "スレッドなし",
        "Pick an agent": "エージェントを選び",
        "and enter a task": "タスクを入力してください",
        "LOCAL ONLY": "ローカルのみ",
        "PARALLEL": "並列",
        "TEAMWORK": "分業",
        "UNDO": "元に戻す",
        "CLEAR": "クリア",
        "ROUTE": "実行順序",
        "click agents in execution order": "実行順にエージェントをクリック",
        "Instruction passed between steps (optional)": "ステップ間で渡す指示（任意）",
        "Search title, agent, cwd": "タイトル・エージェント・作業フォルダを検索",
        "PROJECT": "プロジェクト",
        "Delete this thread?": "このスレッドを削除しますか？",
        "Its local history and output will be removed from Relay.": "Relay に保存されたローカル履歴と出力が削除されます。",
        "Delete": "削除",
        "SAVE": "保存",
        "RENAME": "名前変更",
        "EXPORT": "エクスポート",
        "Export this thread as Markdown": "このスレッドを Markdown として書き出す",
        "Copy this reply": "この回答をコピー",
        "CANCEL": "キャンセル",
        "DELETE": "削除",
        "CHOOSE": "選択",
        "Working directory": "作業フォルダ",
        "MODEL": "モデル",
        "EFFORT": "強度",
        "CODEX MODE": "CODEX モード",
        "Interactive questions enabled": "対話形式の質問を許可",
        "Direct execution": "直接実行",
        "Local multi-CLI workspace": "ローカル マルチ CLI ワークスペース",
        "Thread title": "スレッド名",
        "Waiting for adapter output…": "Adapter の出力を待っています…",
        "RELAY READY": "RELAY 準備完了",
        "unavailable": "利用不可",
        "Enter a task below. Relay stays active after this window closes.": "下にタスクを入力してください。ウインドウを閉じても Relay は動作を続けます。",
        "FOCUS": "フォーカス",
        "Waiting in USER GATE — use FOCUS to respond": "ユーザー操作を待っています。フォーカスして回答してください",
        "RETURN": "実行",
        "CONTINUE": "続ける",
        "Custom response": "自由入力",
        "SENDING…": "送信中…",
        "SEND RESPONSE": "回答を送信",
        "APPROVAL": "承認",
        "INPUT": "入力",
        "ADAPTER MANIFESTS": "ADAPTER 設定",
        "ADD CLI": "CLI を追加",
        "IMPORT": "読み込む",
        "CLOSE": "閉じる",
        "USER DIR": "ユーザーフォルダ",
        "REVEAL": "Finder で表示",
        "USER": "ユーザー",
        "BUILT-IN": "内蔵",
        "EDIT": "編集",
        "ADD LINE CLI": "行形式 CLI を追加",
        "EDIT LINE CLI": "行形式 CLI を編集",
        "Prompt via stdin · output from stdout": "stdin から入力 · stdout へ出力",
        "EXECUTABLE": "実行ファイル",
        "ARGUMENTS · ONE ARGUMENT PER LINE · OPTIONAL": "引数 · 1 行につき 1 個 · 任意",
        "LOCAL MANIFEST": "ローカル設定",
        "SAVING…": "保存中…",
        "CREATE ADAPTER": "ADAPTER を作成",
        "SAVE ADAPTER": "ADAPTER を保存",
        "Chinese": "简体中文",
        "Japanese": "日本語",
        "Manage adapter manifests": "Adapter 設定を管理",
        "Open Relay settings": "Relay の設定を開く",
        "Send one task to several agents in parallel": "同じタスクを複数のエージェントへ並列送信",
        "Pass each completed answer to the next agent": "完了した回答を次のエージェントへ渡す",
        "Clear thread search": "スレッド検索をクリア",
        "Refresh threads": "スレッドを更新",
        "Cancel rename": "名前変更をキャンセル",
        "Delete this local thread": "このローカルスレッドを削除",
        "NO MATCHES": "一致する項目なし",
        "Change the search": "検索条件を変更してください",
        "No threads with this status": "この状態のスレッドはありません",
        "CLEAR SEARCH": "検索をクリア",
        "SHOW ALL": "すべて表示",
        "Some output was truncated after reaching the local history limit.": "ローカル履歴の上限に達したため、一部の出力を省略しました。",
        "BACK TO CHAIN": "チェーンに戻る",
        "BACK TO COMPARE": "比較に戻る",
        "Focused on one chain step": "1 つのチェーンステップを表示中",
        "Focused on one comparison member": "1 つの比較メンバーを表示中",
        "Open this chain step as a normal thread": "このチェーンステップを通常のスレッドとして開く",
        "Open this member as a normal thread": "このメンバーを通常のスレッドとして開く",
        "Click at least two agents to build a chain…": "2 個以上のエージェントをクリックしてチェーンを作成…",
        "Check at least two agents to compare…": "比較するエージェントを 2 個以上選択…",
        "Respond in USER GATE above to continue…": "上のユーザー操作欄で回答して続行…",
        "The selected task is still running…": "選択したタスクは実行中です…",
        "Continue this thread, or type @agent to hand it off…": "このスレッドを続けるか、@agent で引き継ぎ…",
        "Type @agent to hand off, or start a new task…": "@agent で引き継ぐか、新しいタスクを開始…",
        "Remove adapter": "Adapter を削除",
        "Its manifest will be deleted from the user adapter directory.": "設定ファイルがユーザー Adapter フォルダから削除されます。",
        "Create a line-based CLI adapter": "行形式 CLI Adapter を作成",
        "Copy a manifest into the user adapter directory": "設定ファイルをユーザー Adapter フォルダへコピー",
        "Rescan manifests": "設定ファイルを再読み込み",
        "CLI ID · start with a letter or number · then a-z, 0-9, - or _": "CLI ID · 英数字で開始 · 以降は a-z、0-9、-、_ を使用",
        "DISPLAY NAME": "表示名",
        "Relay creates a local manifest and registers it immediately. This simple adapter does not resume CLI-native sessions; import a custom manifest for session or JSONL support.": "Relay はローカル設定を作成してすぐに登録します。この簡易 Adapter は CLI 本来のセッションを再開しません。session または JSONL 対応にはカスタム設定を読み込んでください。",
        "Relay keeps the CLI ID and updates this local manifest immediately. Running tasks keep their existing process; new tasks use the saved executable and arguments.": "Relay は CLI ID を維持したままローカル設定をすぐに更新します。実行中のタスクは既存プロセスを維持し、新しいタスクから保存後の実行ファイルと引数を使用します。"
    ]
}

private struct RelayLanguageKey: EnvironmentKey {
    static let defaultValue = RelayLanguage.chinese
}

extension EnvironmentValues {
    var relayLanguage: RelayLanguage {
        get { self[RelayLanguageKey.self] }
        set { self[RelayLanguageKey.self] = newValue }
    }
}
