import Foundation
import Testing
@testable import RelayGUI

@Suite("RelayLocalizationTests")
struct RelayLocalizationTests {
    @Test("defaults to Chinese and persists Japanese")
    func persistsSelectedLanguage() throws {
        let suiteName = "RelayLocalizationTests.\(UUID().uuidString)"
        let defaults = try #require(UserDefaults(suiteName: suiteName))
        defer { defaults.removePersistentDomain(forName: suiteName) }

        #expect(RelayLanguage.load(from: defaults) == .chinese)
        RelayLanguage.japanese.save(to: defaults)
        #expect(RelayLanguage.load(from: defaults) == .japanese)
        RelayLanguage.english.save(to: defaults)
        #expect(RelayLanguage.load(from: defaults) == .english)
    }

    @Test("English is the identity table over the key strings")
    func englishPassthroughAndFormatters() {
        let english = RelayCopy(language: .english)

        #expect(english.text("Settings") == "Settings")
        #expect(english.text("PROJECTS") == "PROJECTS")
        #expect(english.text("Open Claude and Codex for this project")
            == "Open Claude and Codex for this project")
        #expect(english.taskStatus(.waitingForInput) == "Awaiting input")
        #expect(english.daemonState(.online) == "ONLINE")
        #expect(english.agentHealth(.ready) == "READY")
        #expect(english.threadFilter(.active) == "Active")
        #expect(english.outputKind(.assistant) == "Agent")
        #expect(english.codexMode(.plan) == "Plan")
        #expect(english.chainPlaceholder(count: 3) == "Task to send through 3 relay steps…")
        #expect(english.comparePlaceholder(count: 2) == "Task to send to 2 agents in parallel…")
        #expect(english.taskPlaceholder(agentName: "Claude") == "Describe a task for Claude…")
        #expect(RelayLanguage.english.nativeName == "English")
    }

    @Test("provides Chinese and Japanese interface copy")
    func translatesInterfaceCopy() {
        let chinese = RelayCopy(language: .chinese)
        let japanese = RelayCopy(language: .japanese)

        #expect(chinese.text("Settings") == "设置")
        #expect(japanese.text("Settings") == "設定")
        #expect(chinese.taskStatus(.waitingForInput) == "等待输入")
        #expect(japanese.taskStatus(.waitingForInput) == "入力待ち")
        #expect(chinese.codexMode(.plan) == "计划")
        #expect(japanese.codexMode(.plan) == "計画")
        #expect(chinese.text("REVIEW") == "待看")
        #expect(japanese.text("REVIEW") == "未読")
        #expect(chinese.text("NEXT") == "下一项")
        #expect(japanese.text("NEXT") == "次へ")
        #expect(chinese.text("BACK") == "返回")
        #expect(japanese.text("BACK") == "戻る")
        #expect(chinese.text("CONTEXT FORK") == "上下文分叉")
        #expect(japanese.text("CONTEXT FORK") == "コンテキスト分岐")
        #expect(chinese.text("FILL ⟨N⟩ TARGETS · DOES NOT RUN") == "填入 ⟨N⟩ 个目标 · 不执行")
        #expect(japanese.text("FILL ⟨N⟩ TARGETS · DOES NOT RUN") == "⟨N⟩ 件に入力 · 実行しません")
        #expect(chinese.text("RESULT CONFLUENCE") == "结果汇流")
        #expect(japanese.text("RESULT CONFLUENCE") == "結果コンフルエンス")
        #expect(chinese.text("CAPTURE CURRENT SCREENS") == "汇流当前画面")
        #expect(japanese.text("CAPTURE CURRENT SCREENS") == "現在の画面を集約")
        #expect(chinese.text("RESULT ARBITRATION") == "结果裁决")
        #expect(japanese.text("RESULT ARBITRATION") == "結果判定")
        #expect(chinese.text("ARBITRATE RESULTS") == "裁决这些结果")
        #expect(japanese.text("ARBITRATE RESULTS") == "結果を判定")
        #expect(chinese.text("PAYLOAD PREFLIGHT") == "载荷预检")
        #expect(japanese.text("PAYLOAD PREFLIGHT") == "ペイロード事前確認")
        #expect(chinese.text("FULL") == "完整")
        #expect(japanese.text("FULL") == "全文")
        #expect(chinese.text("TAIL KEPT") == "已截尾")
        #expect(japanese.text("TAIL KEPT") == "末尾を保持")
        #expect(chinese.text("UTF-8 BYTES · NO TOKEN GUESS") == "UTF-8 字节 · 不猜 token")
        #expect(japanese.text("UTF-8 BYTES · NO TOKEN GUESS") == "UTF-8 バイト・トークン推測なし")
        #expect(chinese.text("Enter an instruction to preview exact local bytes") == "输入裁决指令后预检准确的本地字节数")
        #expect(japanese.text("Enter an instruction to preview exact local bytes") == "判定指示を入力すると正確なローカルバイト数を確認できます")
        #expect(chinese.text("ARBITRATION SOURCES") == "裁决来源")
        #expect(japanese.text("ARBITRATION SOURCES") == "判定元")
        #expect(chinese.text("BACK TO ARBITER REVIEW") == "返回裁决核对")
        #expect(japanese.text("BACK TO ARBITER REVIEW") == "判定先の確認に戻る")
        #expect(chinese.text("VIEW ⟨N⟩ FROZEN SOURCES · ⟨BYTES⟩ B") == "查看 ⟨N⟩ 个冻结来源 · ⟨BYTES⟩ B")
        #expect(japanese.text("VIEW ⟨N⟩ FROZEN SOURCES · ⟨BYTES⟩ B") == "固定元 ⟨N⟩ 件を表示・⟨BYTES⟩ B")
        #expect(chinese.text("CHECK LIVE DRIFT") == "检查实时变化")
        #expect(japanese.text("CHECK LIVE DRIFT") == "ライブ差分を確認")
        #expect(chinese.text("UNCHANGED") == "未变化")
        #expect(japanese.text("UNCHANGED") == "変更なし")
        #expect(chinese.text("CHANGED") == "已变化")
        #expect(japanese.text("CHANGED") == "変更あり")
        #expect(chinese.text("DECISION SEAL") == "决策封存")
        #expect(japanese.text("DECISION SEAL") == "判定記録")
        #expect(chinese.text("SEAL RESULT") == "封存结果")
        #expect(japanese.text("SEAL RESULT") == "結果を固定")
        #expect(chinese.text("VIEW SEALED RESULT") == "查看封存结果")
        #expect(japanese.text("VIEW SEALED RESULT") == "固定結果を表示")
        #expect(chinese.text("DECISION LIBRARY") == "决策库")
        #expect(japanese.text("DECISION LIBRARY") == "判定ライブラリ")
        #expect(chinese.text("Close decision library") == "关闭决策库")
        #expect(japanese.text("Close decision library") == "判定ライブラリを閉じる")
        #expect(chinese.text("SAVE PRIVATE CHECKPOINT") == "保存私有检查点")
        #expect(japanese.text("SAVE PRIVATE CHECKPOINT") == "非公開チェックポイントを保存")
        #expect(chinese.text("MOVE TO TRASH") == "移入废纸篓")
        #expect(japanese.text("MOVE TO TRASH") == "ゴミ箱へ移動")
        #expect(chinese.text("CHECKPOINT REPLAY") == "检查点重裁决")
        #expect(japanese.text("CHECKPOINT REPLAY") == "チェックポイント再判定")
        #expect(chinese.text("RE-ARBITRATE FROM CHECKPOINT") == "从检查点重新裁决")
        #expect(japanese.text("RE-ARBITRATE FROM CHECKPOINT") == "チェックポイントから再判定")
        #expect(chinese.text("CONTINUE FROM DECISION") == "从此决策继续")
        #expect(japanese.text("CONTINUE FROM DECISION") == "この判定から続行")
        #expect(chinese.text("DECISION → ACTION BRIDGE") == "决策 → 行动桥")
        #expect(japanese.text("DECISION → ACTION BRIDGE") == "判定 → 実行ブリッジ")
        #expect(chinese.text("FILL TARGET · DOES NOT RUN") == "填入目标 · 不执行")
        #expect(japanese.text("FILL TARGET · DOES NOT RUN") == "対象に入力 · 実行しません")
        #expect(chinese.text("DERIVED CHECKPOINT · 0600") == "派生检查点 · 0600")
        #expect(japanese.text("DERIVED CHECKPOINT · 0600") == "派生チェックポイント・0600")
        #expect(chinese.text("VIEW PARENT") == "查看父检查点")
        #expect(japanese.text("VIEW PARENT") == "親チェックポイントを表示")
        #expect(chinese.text("DECISION DELTA") == "决策差异")
        #expect(japanese.text("DECISION DELTA") == "判定差分")
        #expect(chinese.text("COMPARE RESULTS") == "对比结果")
        #expect(japanese.text("COMPARE RESULTS") == "結果を比較")
        #expect(chinese.text("BACK TO DERIVED") == "返回派生检查点")
        #expect(japanese.text("BACK TO DERIVED") == "派生チェックポイントへ戻る")
        #expect(chinese.text("LINEAGE") == "决策血缘")
        #expect(japanese.text("LINEAGE") == "判定系譜")
        #expect(chinese.text("PARENT MISSING") == "父记录缺失")
        #expect(japanese.text("PARENT MISSING") == "親記録がありません")
        #expect(chinese.text("CYCLE BLOCKED") == "已阻断循环")
        #expect(japanese.text("CYCLE BLOCKED") == "循環を遮断")
        #expect(chinese.text("COMPARE LINEAGE") == "比较血缘节点")
        #expect(japanese.text("COMPARE LINEAGE") == "系譜ノードを比較")
        #expect(chinese.text("FAMILY LIMIT") == "已达家族上限")
        #expect(japanese.text("FAMILY LIMIT") == "系譜上限に到達")
        #expect(chinese.text("REFERENCE RESULT") == "参考结果")
        #expect(japanese.text("REFERENCE RESULT") == "参照結果")
        #expect(chinese.text("CURRENT RESULT") == "当前结果")
        #expect(japanese.text("CURRENT RESULT") == "現在の結果")
        #expect(chinese.text("SEARCH DECISIONS") == "搜索决策")
        #expect(japanese.text("SEARCH DECISIONS") == "判定を検索")
        #expect(chinese.text("No matching decisions") == "没有匹配的决策")
        #expect(japanese.text("No matching decisions") == "一致する判定はありません")
        #expect(chinese.text("Clear decision search") == "清除决策搜索")
        #expect(japanese.text("Clear decision search") == "判定検索をクリア")
        #expect(chinese.text("PIN DECISION") == "置顶决策")
        #expect(japanese.text("PIN DECISION") == "判定をピン留め")
        #expect(chinese.text("EDIT LABEL") == "编辑标签")
        #expect(japanese.text("EDIT LABEL") == "ラベルを編集")
        #expect(chinese.text("SAVE LABEL") == "保存标签")
        #expect(japanese.text("SAVE LABEL") == "ラベルを保存")
        #expect(chinese.text("EVIDENCE READ ONLY · PRIVATE 0600") == "证据只读 · 私有文件 0600")
        #expect(japanese.text("EVIDENCE READ ONLY · PRIVATE 0600") == "証拠は読み取り専用・非公開 0600")
        #expect(chinese.text("Explicit saves only · private files 0600 · deletion moves to Trash") == "仅显式保存 · 私有文件 0600 · 删除会移入废纸篓")
        #expect(japanese.text("Explicit saves only · private files 0600 · deletion moves to Trash") == "明示的な保存のみ・非公開ファイル 0600・削除はゴミ箱へ移動")
        #expect(chinese.text("Focus latest terminal output · ⌥⌘J") == "跳到最近输出的终端 · ⌥⌘J")
        #expect(japanese.text("Focus latest terminal output · ⌥⌘J") == "最新の出力ターミナルへ移動 · ⌥⌘J")
        #expect(chinese.text("Return to ⟨CLI⟩ · ⌥⌘K") == "返回 ⟨CLI⟩ · ⌥⌘K")
        #expect(japanese.text("Return to ⟨CLI⟩ · ⌥⌘K") == "⟨CLI⟩ に戻る · ⌥⌘K")
        #expect(chinese.text("Terminal output needs review") == "此终端有待查看输出")
        #expect(japanese.text("Terminal output needs review") == "このターミナルに未確認の出力があります")
        #expect(chinese.text("FILL ONLY · DOES NOT RUN") == "仅填入 · 不执行")
        #expect(japanese.text("FILL ONLY · DOES NOT RUN") == "入力のみ・実行しません")
        #expect(chinese.text("CONFIRM PROMPT") == "请确认输入框")
        #expect(japanese.text("CONFIRM PROMPT") == "入力欄を確認")
        #expect(chinese.text("PROMPT REVIEW") == "提示词核对")
        #expect(japanese.text("PROMPT REVIEW") == "プロンプト確認")
        #expect(chinese.text("DECISION BRIEF REVIEW") == "决策简报核对")
        #expect(japanese.text("DECISION BRIEF REVIEW") == "判定ブリーフ確認")
        #expect(chinese.text("BACK TO DECISION") == "返回决策")
        #expect(japanese.text("BACK TO DECISION") == "判定へ戻る")
        #expect(chinese.text("CAPTURE ACTION RECEIPT") == "冻结行动回执")
        #expect(japanese.text("CAPTURE ACTION RECEIPT") == "アクション受領票を固定")
        #expect(chinese.text("DECISION ACTION RECEIPT") == "决策行动回执")
        #expect(japanese.text("DECISION ACTION RECEIPT") == "判定アクション受領票")
        #expect(chinese.text("CURRENT SCREENS · NOT SUCCESS PROOF") == "当前画面 · 不代表执行成功")
        #expect(japanese.text("CURRENT SCREENS · NOT SUCCESS PROOF") == "現在の画面・成功の証明ではありません")
        #expect(chinese.text("SAVE PRIVATE RECEIPT") == "保存私有回执")
        #expect(japanese.text("SAVE PRIVATE RECEIPT") == "非公開受領票を保存")
        #expect(chinese.text("RECOVER IN LIVE CLI") == "在实时 CLI 中恢复")
        #expect(japanese.text("RECOVER IN LIVE CLI") == "ライブ CLI で復元")
        #expect(chinese.text("RECEIPT → LIVE CLI RECOVERY") == "回执 → 实时 CLI 恢复")
        #expect(japanese.text("RECEIPT → LIVE CLI RECOVERY") == "受領票 → ライブ CLI 復元")
        #expect(chinese.text("ACTION RECOVERY REVIEW") == "行动恢复核对")
        #expect(japanese.text("ACTION RECOVERY REVIEW") == "アクション復元確認")
        #expect(chinese.text("BACK TO ACTION RECEIPT") == "返回行动回执")
        #expect(japanese.text("BACK TO ACTION RECEIPT") == "アクション受領票へ戻る")
        #expect(chinese.text("CAPTURE RECOVERY CHANGE") == "截取恢复变化")
        #expect(japanese.text("CAPTURE RECOVERY CHANGE") == "復元変化を取得")
        #expect(chinese.text("RECOVERY CHANGE RECEIPT") == "恢复变化回执")
        #expect(japanese.text("RECOVERY CHANGE RECEIPT") == "復元変化受領票")
        #expect(chinese.text("VISIBLE SCREEN CHANGE") == "可见画面变化")
        #expect(japanese.text("VISIBLE SCREEN CHANGE") == "表示画面の変化")
        #expect(chinese.text("SAVE PRIVATE RECOVERY CHANGE") == "保存私有恢复变化")
        #expect(japanese.text("SAVE PRIVATE RECOVERY CHANGE") == "非公開の復元変化を保存")
        #expect(chinese.text("CONTINUE CHANGE IN LIVE CLI") == "把变化接力到实时 CLI")
        #expect(japanese.text("CONTINUE CHANGE IN LIVE CLI") == "復元変化をライブ CLI に引き継ぐ")
        #expect(chinese.text("RECOVERY CHANGE HANDOFF REVIEW") == "恢复变化接力核对")
        #expect(japanese.text("RECOVERY CHANGE HANDOFF REVIEW") == "復元変化引き継ぎ確認")
        #expect(chinese.text("BACK TO RECOVERY CHANGE") == "返回恢复变化")
        #expect(japanese.text("BACK TO RECOVERY CHANGE") == "復元変化へ戻る")
        #expect(chinese.text("RECOVERY CHANGE WITNESS") == "恢复变化见证")
        #expect(japanese.text("RECOVERY CHANGE WITNESS") == "復元変化の確認記録")
        #expect(chinese.text("CAPTURE RECOVERY WITNESS") == "截取恢复见证")
        #expect(japanese.text("CAPTURE RECOVERY WITNESS") == "復元確認記録を取得")
        #expect(chinese.text("SUPPORTS CHANGE") == "支持变化")
        #expect(japanese.text("SUPPORTS CHANGE") == "変化を支持")
        #expect(chinese.text("RAISES CONCERN") == "发现问题")
        #expect(japanese.text("RAISES CONCERN") == "懸念あり")
        #expect(chinese.text("INCONCLUSIVE") == "无法判断")
        #expect(japanese.text("INCONCLUSIVE") == "判断保留")
        #expect(chinese.text("SAVE PRIVATE WITNESS") == "保存私有见证")
        #expect(japanese.text("SAVE PRIVATE WITNESS") == "非公開の確認記録を保存")
        #expect(chinese.text("COMPARE WITNESSES") == "对照见证")
        #expect(japanese.text("COMPARE WITNESSES") == "確認記録を比較")
        #expect(chinese.text("USER LABELS DIFFER") == "人工标注分歧")
        #expect(japanese.text("USER LABELS DIFFER") == "ユーザー分類が相違")
        #expect(chinese.text("CHECKED · NEXT") == "已检查 · 下一窗")
        #expect(japanese.text("CHECKED · NEXT") == "確認済み・次へ")
        #expect(chinese.text("RETURN NOT DETECTED") == "未检测到回车")
        #expect(japanese.text("RETURN NOT DETECTED") == "RETURN は未検出")
        #expect(chinese.text("Return detected; Relay did not send it") == "检测到用户回车 · 不是 Relay 发送")
        #expect(japanese.text("Return detected; Relay did not send it") == "ユーザーの Return を検出・Relay は送信していません")
        #expect(chinese.text("Resume prompt review · ⟨N⟩ left") == "继续提示词核对 · 还剩 ⟨N⟩ 个")
        #expect(japanese.text("Resume prompt review · ⟨N⟩ left") == "プロンプト確認を再開・残り ⟨N⟩")
        #expect(chinese.text("END REVIEW") == "结束核对")
        #expect(japanese.text("END REVIEW") == "確認を終了")
    }

    @Test("keeps unknown CLI text unchanged")
    func preservesUnknownText() {
        let copy = RelayCopy(language: .japanese)
        #expect(copy.text("MODEL_OUTPUT_FROM_CLI") == "MODEL_OUTPUT_FROM_CLI")
    }
}
